### ISSUE TITLE
Support array valued attributes

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-proto#106]
See https://github.com/open-telemetry/opentelemetry-specification/pull/368

**Comment by Oberon00** [comment]
Should this get a milestone? Seems quite overdue.

**Comment by arminru** [comment]
> Should this get a milestone? Seems quite overdue.

Quite overdue (and apparently overlooked), yes. Currently there are no milestones defined/used in this repo, however.

**Comment by tigrannajaryan** [comment]
I'll take this.
