### ISSUE TITLE
Review Data Model (Protos)

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-proto#11]
Everyone, please review the current protobuf and metadata definitions and leave comments here.

**Comment by tmc** [comment]
It's a bit unfortunate that there isn't a great way to attach structured nested metadata as attributes. Perhaps consider supporting Any values as a means of extension?

**Comment by bogdandrutu** [comment]
@tmc we discuss  to add some support of AttributeValue to be another Map<String, AttributeValue> is that enough?

We do not want to add Any because that means that a backend cannot analyze the data, maybe not even display them.

**Comment by tmc** [comment]
I imagine that for many use cases allowing maps would suffice.

**Comment by tete17** [comment]
Sorry to step into this conversation but is the idea of this project that all other language implementations to use this definition as a basis of is it only for the Java one?

I do not see it in use as a submodule for the node-js one

**Comment by SergeyKanzhelev** [comment]
Seems to be complete. See https://github.com/open-telemetry/oteps/pull/59 where we extensively reviewed it.

Closing.
