### ISSUE TITLE
Dictionary of attribute names

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-proto#12]
Will we need at some point a dictionary of standard attribute names and use indexes instead of names for the attributes collection? It may save a lot of bandwidth, but will require to change the type for now from `string` to `AttributeKey`.

**Comment by jmacd** [comment]
I think we should compare and contrast with a good compression library? Compression is cheap and will avoid the need for this sort of complexity.

**Comment by SergeyKanzhelev** [comment]
do you know if there is compression in grpc/proto?

**Comment by bogdandrutu** [comment]
@SergeyKanzhelev yes. You can use gzip and few other options.

**Comment by SergeyKanzhelev** [comment]
@tigrannajaryan are we using compression in our protocol? What do you think about this issues? I'm happy to close it if we have some note on how to gzip or why we do not want to gzip

**Comment by SergeyKanzhelev** [comment]
@tigrannajaryan assigning to you if you don't mind

**Comment by tigrannajaryan** [comment]
@SergeyKanzhelev thanks. I addressed this in https://github.com/open-telemetry/oteps/pull/59
Once that is approved I will update Span proto definition in this repo.

**Comment by tigrannajaryan** [comment]
Regarding compression: OTLP uses gRPC and compression is supported out of the box.
