### ISSUE TITLE
ExportTraceServiceRequest

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-proto#123]
Currently the ExportTraceServiceRequest is missing `node` and `resource`
Is this going to be implemented, was it removed or ?
https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-exporter-collector/src/types.ts#L92

**Comment by obecny** [comment]
cc @mayurkale22 @dyladan

**Comment by tigrannajaryan** [comment]
Node is removed. Resource is part of ResourceSpans that is part of ExportTraceServiceRequest.

**Comment by Oberon00** [comment]
I think you could say that "node" is also (slated to become) part of resources.

**Comment by tigrannajaryan** [comment]
> I think you could say that "node" is also (slated to become) part of resources.

Yes.

**Comment by SergeyKanzhelev** [comment]
@obecny please reopen if you have more questions
