### ISSUE TITLE
Label keys/values in diagram in metrics.proto do not match the proto specification

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-proto#124]
The [diagram](https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/metrics/v1/metrics.proto#L46-L77) in metrics.proto does not match the specification.
Diagram indicates that Descriptor contains only Keys while the proto say it contains [keys and values](https://github.com/open-telemetry/opentelemetry-proto/blob/d496c80b353bc4a4f754ae686b59ca3c41de0946/opentelemetry/proto/metrics/v1/metrics.proto#L165-L167) that are common to all data points.

**Comment by tigrannajaryan** [comment]
Yes, @bogdandrutu changed the proto recently. The diagram needs an update.

**Comment by tigrannajaryan** [comment]
If only I remembered what did I use to create the diagram :-)
Let me see if I can dig it.

**Comment by bogdandrutu** [comment]
@tigrannajaryan let me know if you find how you created the diagram.

**Comment by tigrannajaryan** [comment]
@bogdandrutu I think I used this https://textik.com
