### ISSUE TITLE
Take beta declaration serious or remove it.

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-proto#128]
https://github.com/open-telemetry/opentelemetry-proto/pull/103 declared large parts of the protocols as beta, but purely cosmetic yet breaking changes like https://github.com/open-telemetry/opentelemetry-proto/pull/120 were still incorporated. What's the definition of beta, this repository is following?
(I think our official definition is a bit over the top https://github.com/open-telemetry/community/blob/master/maturity-matrix.yaml#L43-L49)

**Comment by tigrannajaryan** [comment]
I agree, we should take beta declaration seriously. Note that we are still allowed to make braking changes but very infrequently. According to API maturity level [definitions](https://github.com/open-telemetry/community/blob/master/maturity-matrix.yaml):
>"beta" maturity APIs should not introduce backwards-incompatible changes
 more than once every three months; and when those changes are introduced, the
 authors will make a best effort to provide compatibility bridges.

Given that there are no existing OTLP implementations yet arguably we are still OK with making changes, but I agree, we should all begin to respect the definition of "beta" or agree that it is too early and remove the label. The later will have ramifications: work that depends on protocol being "beta"-stable will be halted.

**Comment by SergeyKanzhelev** [comment]
should we revert the #120 than or keep it? I also filed an issue that the change may not be great for interoperability

**Comment by Oberon00** [comment]
Good question. Actually, I think a (beta) release should be tagged (currently there are no tags at all https://github.com/open-telemetry/opentelemetry-proto/tags), otherwise the beta declaration is either meaningless or every commit counts as release.

**Comment by SergeyKanzhelev** [comment]
Totally agree. Tag would be very helpful. @bogdandrutu revert or keep the change?

**Comment by tigrannajaryan** [comment]
I suggest we keep #120. It is done and already used by dependent repos, reverting is worse.

**Comment by Oberon00** [comment]
So the action item here is to tag a release?

**Comment by Oberon00** [comment]
Since a release was tagged now, are we fine with keeping the beta-"promise" in the README?

CC @bogdandrutu

**Comment by bogdandrutu** [comment]
What does "beta promise" means?

**Comment by Oberon00** [comment]
@bogdandrutu See @tigrannajaryan's comment: https://github.com/open-telemetry/opentelemetry-proto/issues/128#issuecomment-599686709

**Comment by tigrannajaryan** [comment]
I think we recently made a sufficient efforts to be serious about maturity declarations. I suggest that we close this issue.
