### ISSUE TITLE
Should we revert tracestate -> trace_state rename?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-proto#130]
See comment here: https://github.com/open-telemetry/opentelemetry-proto/pull/120/files#r393369691

**Comment by Oberon00** [comment]
Please see #128: I wouldn't do such renamings anymore now. Also I think the motivation for W3C was to be compatible with protocols other than HTTP. This does not apply to protobuf field names.

**Comment by bogdandrutu** [comment]
I would suggest to not do that.
