### ISSUE TITLE
Inconsistent Naming_CONVENTIONS for enum values

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-proto#131]
Looking at

https://github.com/open-telemetry/opentelemetry-proto/blob/e76584d22418e37ae9a1ee782ce56ae7e2651ccf/opentelemetry/proto/trace/v1/trace.proto#L106

vs

https://github.com/open-telemetry/opentelemetry-proto/blob/e76584d22418e37ae9a1ee782ce56ae7e2651ccf/opentelemetry/proto/trace/v1/trace.proto#L239

it seems we need to decide on a convention to follow when naming enum values.

**Comment by tigrannajaryan** [comment]
Same discrepancy in the spec that describes the corresponding enums :-)
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#statuscanonicalcode

See SpanKind vs StatusCanonicalCode in the spec.

**Comment by bogdandrutu** [comment]
It will be good to fix this in both specs and here.

**Comment by bogdandrutu** [comment]
The proto part is done.
