### ISSUE TITLE
proto is missing serviceName

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-proto#135]
Either serviceName is missing from proto or the https://github.com/open-telemetry/opentelemetry-collector doesn't support that, or both of them are missing this info. 
This is causing for example in zipkin the trace to look like this

https://imgur.com/a/uB5dSSo

**Comment by tigrannajaryan** [comment]
OpenTelemetry specification defines that the service name should be stored as an attribute "service.name": https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-resource-semantic-conventions.md#service

Any sources that have hard-coded fields for the server name need to translate it into an attribute when received by the Collector and the exporters need to do the reverse translation. This is how all fields that do not have exact matches between formats (including Collector's internal format) are handled in the Collector.

If this is how Collector behaves today then it needs to be files as a bug against Collector's Zipkin receiver or exporter implementation. Best to submit an issue with more details (reproduction steps) here https://github.com/open-telemetry/opentelemetry-collector/issues

**Comment by obecny** [comment]
ok thx, then this was a matter of adding a "service.name" attribute to `Resource`, it is working now

**Comment by tigrannajaryan** [comment]
Closing as resolved. Please reopen if needed.

**Comment by huntc** [comment]
I notice that the service name is explicitly provided to the Jaeger and Zipkin exporters. Should these exporters be updated to use resources for the service name?
