### ISSUE TITLE
Description for traceId, spanId, parentId is wrong

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-proto#136]
The description for traceId, spanId, parentId says it should be bytes, however it works only if traceId is base64

https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/trace/v1/trace.proto#L58
https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/trace/v1/trace.proto#L68
https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/trace/v1/trace.proto#L83

This is misleading and was hard to debug what is the problem

**Comment by tigrannajaryan** [comment]
It should not be limited to base64. It is declared as bytes and any byte sequence should work.

**Comment by obecny** [comment]
but it doesn't work with bytes, only with base64

**Comment by Oberon00** [comment]
Doesn't work with what? That' probably the receivers fault, not the protocol's. So this issue is probably in the wrong repository.

**Comment by obecny** [comment]
the proto format says that traceId, spanId and parentId should be bytes, but if you send the data using bytes instead of base64, the opentelemetry collector doesn't work. So this is either wrong description here or opentelemetry collector bug.

**Comment by Oberon00** [comment]
I'd say, by definition, the opentelemetry collector has a bug. 😃

**Comment by obecny** [comment]
I have created issue there too let's see who will do the fix ;)

**Comment by bogdandrutu** [comment]
@obecny Are you using the JSON with grpc gateway? If yes that is not a bug is the proto limitation, see https://github.com/open-telemetry/opentelemetry-proto/issues/129

**Comment by bogdandrutu** [comment]
See here as well https://developers.google.com/protocol-buffers/docs/proto3#json - bytes are mapped as base64 in JSON representation.

**Comment by obecny** [comment]
@bogdandrutu yes grpc with json.  I don't know about the limitation etc. but when I was implementing this it was saying use bytes which I did, but then the error from collector was not enough to be able to understand what is the problem. We can argue where is the bug, but simply adding some explanation in proto repo that with json you should use base64 would probably save some hours of debugging and trying to figure out what's the problem and if either format is wrong or the receiver - which btw has even much worse documentation and outdated :).

**Comment by bogdandrutu** [comment]
https://github.com/open-telemetry/opentelemetry-collector/pull/980#discussion_r426844996 will resolve this issue.
