### ISSUE TITLE
Add benchmarks to proto

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-proto#138]
I have benchmarks in my personal repo https://github.com/tigrannajaryan/exp-otelproto

This contains both microbenchmarks for proto encoding/decoding and also full protocol implementations (OTLP, OpenCensus and others).

I am happy to donate this provided that I get merging rights on this subtree of the repo. I need to be able quickly iterate on this and waiting for regular approvals for changes in benchmarks is not going to work for the upcoming plans I have for iterating on logs support in OTLP. It will just slow me down too much.

If we can introduce CODEOWNERS and give me merging rights for a subdirectory where the benchmarks reside I will be glad to move it to this repo so that other people who need to work on the proto can also benchmark their changes.

If there are concerns about giving merging rights I am happy to keep the benchmarks in my repo, no problem.

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-approvers what do you think?

**Comment by Oberon00** [comment]
You did not mention "Go" anywhere, but it seems you are actually benchmarking only the Go code for parsing/writing the protocol.

The protocol will have different performances depending on the protobuf implementation and language. I think you can't sensibly benchmark the protocol itself, only writers and readers based on it. And I think these should be benchmarked in their respective language repositories.

Related #79.

**Comment by tigrannajaryan** [comment]
>You did not mention "Go" anywhere, but it seems you are actually benchmarking only the Go code for parsing/writing the protocol.
>The protocol will have different performance depending on the protobuf implementation and language. I think you can't sensibly benchmark the protocol itself, only writers and readers based on it. And I think these should be benchmarked in their respective language repositories.

@Oberon00 yes, that's correct and I am also not happy that it has been limited to Go so far. It would be nice to add other languages to benchmarks. It would be good if other contributors added benchmarks for other languages.

**Comment by ThomsonTan** [comment]
@tigrannajaryan if we don't want to limit the proto benchmark to Go, could we add this to below benchmark spec which recommends other OTLP SDKs to implement the same set of benchmark measurement?

https://github.com/open-telemetry/opentelemetry-specification/pull/748

**Comment by tigrannajaryan** [comment]
Yes, the benchmark implementation in https://github.com/tigrannajaryan/exp-otelproto can be extended to other languages. I will not be able to do that myself but if there are other contributors will to do that then that would be great.

**Comment by tigrannajaryan** [comment]
Closing since there has been no interest in this.
