### ISSUE TITLE
Create a Docker image with toolset for compiling proto files

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-proto#142]
The current process requires local install of protoc, which is far from ideal. Consider creating a stable Docker image with the build tools, similar to https://github.com/jaegertracing/docker-protobuf.

**Comment by bogdandrutu** [comment]
Done.

**Comment by yurishkuro** [comment]
@santiagorr so for comparison, in Jaeger we are also using Docker image with protoc and plugins built into it. Our CI to generate proto types takes a few seconds. Building the Docker image itself takes 4+hrs. Basically, rebuilding `protoc` from source every time in the CI is very-very slow.

**Comment by santiagorr** [comment]
> @santiagorr so for comparison, in Jaeger we are also using Docker image with protoc and plugins built into it. Our CI to generate proto types takes a few seconds. Building the Docker image itself takes 4+hrs. Basically, rebuilding `protoc` from source every time in the CI is very-very slow.

Thanks for your answer! And I understand your use case. For the opentelemetry-proto debian packaging, I am not compiling the protoc from source, but installing the protobuf-compiler binary package as build dependency (so it takes some minutes, no hours!).

From my PoV, it would be great if the Makefile provides targets for both: building relying on docker, and building from a local /usr/bin/protoc. Any strong objection to file an issue to request that?
