### ISSUE TITLE
Add comment about CUMULATIVE edge case

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-proto#143]
One edge case that probably we should document is if one implementation decides to use `CUMULATIVE` and resets the `start_time` every export interval making this type essentially a `DELTA`. What should we recommend/do when in this case?

_Originally posted by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-proto/pull/140_

**Comment by jmacd** [comment]
It's not clear why we should be concerned about this. This looks like a valid transformation, although it is sure to cause performance pains in some systems, for two reasons:

1. The client will have to remember the last value to correctly transform the cumulative into the delta representation.
2. A server that expects cumulative inputs will see each delta as a new timeseries, unless it has code to convert deltas back to cumulatives by comparing start_times and appending when possible.

Nevertheless, it's possible to reconstruct the correct state of the world from the data in this case. WAI?

**Comment by bogdandrutu** [comment]
My idea was just to add a statement that clarifies that this is valid but not recommended.
