### ISSUE TITLE
Allow histograms to specify negative bucket bounds

### ISSUE THREAD

**Issue by x13n** [open-telemetry/opentelemetry-proto#156]
According to the proto documentation, histogram bucket bounds [can only be positive](https://github.com/open-telemetry/opentelemetry-proto/blob/b54688569186e0b862bf7462a983ccf2c50c0547/opentelemetry/proto/metrics/v1/metrics.proto#L362-L385), which makes it impossible for OpenTelemetry to be fully compatible with Prometheus, which [allows negative bounds as well](https://prometheus.io/docs/practices/histograms/#count-and-sum-of-observations).

Prometheus receiver doesn't respect this and sends negative bucket bounds down OpenTelemetry collector pipelines anyway. This can lead to bugs, as processors/exporters can make incorrect assumptions about the data (in fact, at least Stackdriver exporter already does).

This is a request to extend OpenTelemetry data model to treat first histogram bucket as `(-inf, buckets[0])` instead of `[0, buckets[0])`.

/cc @bogdandrutu @rghetia @nilebox @mayurkale22

**Comment by nilebox** [comment]
Should this be covered by the spec?
e.g. https://github.com/open-telemetry/oteps/pull/89, which mentions compatibility with Prometheus histograms.

**Comment by bogdandrutu** [comment]
Please draft a PR.

**Comment by jmacd** [comment]
> Should this be covered by the spec?

I think of this as an OTLP issue, not a spec issue.

**Comment by x13n** [comment]
I drafted a PR, please take a look: https://github.com/open-telemetry/opentelemetry-proto/pull/163
