### ISSUE TITLE
Release v0.4.0 to match Collector v0.4.0

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-proto#161]
There is a `v0.3.0` tag matching Collector v0.3.0 (previous release), but no tag `v0.4.0`.

If we pin OTLP versioning to the collector releases, we should tag `v0.4.0` matching the git submodule commit used by Collector v0.4.0 in https://github.com/open-telemetry/opentelemetry-collector/tree/v0.4.0/internal/data (`/opentelemetry-proto` Git submodule)

**Comment by nilebox** [comment]
@owais if the collector release process is documented somewhere, it should include releasing `opentelemetry-proto` as a prerequisite.

@bogdandrutu @tigrannajaryan  If the plan for OTLP to have independent release versioning, then Collector should only use released versions of `opentelemetry-proto` to make sure we are able to guarantee compatibility between SDKs and Collector.

See https://github.com/open-telemetry/opentelemetry-proto/issues/79#issuecomment-647833945

**Comment by tigrannajaryan** [comment]
I do not think we want to tie versions of Collector and Proto. They evolve at different paces.

> If the plan for OTLP to have independent release versioning, then Collector should only use released versions of opentelemetry-proto to make sure we are able to guarantee compatibility between SDKs and Collector.

This is a good suggestion.

>if the collector release process is documented somewhere, it should include releasing opentelemetry-proto as a prerequisite.

Why is this needed? It is not necessarily a prerequisite if the Collector does not want to use any changes introduced in opentelemetry-proto since the last release.

I think your first suggestion is sufficient: Collector and SDKs to only use released versions of opentelemetry-proto.

**Comment by tigrannajaryan** [comment]
v0.4.0 released: https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.4.0

**Comment by tigrannajaryan** [comment]
I am working on incorporating this in the Collector now: https://github.com/open-telemetry/opentelemetry-collector/pull/1142

**Comment by tigrannajaryan** [comment]
In the past we were not very strict with changes and releases and had quite relaxed attitude towards breaking changes. 

I believe we need to be significantly more careful going forward, particularly with this repo.

I agree that we need to make numbered releases from this repo and all other repos that depend on this repo must only refer to the numbered releases in this repo. In addition all other repos may document which version of this repo they implement.

And it will be much nicer to have a centralized matrix showing versions of proto implemented by each repo - SDK or Collector. We just need to find a good way to maintain such matrix.

**Comment by tigrannajaryan** [comment]
Closing this since the release is done.

**Comment by nilebox** [comment]
@tigrannajaryan `v0.4.0` is shown as "pre-release", and as a result the `v0.3.0` is still marked as the "latest release" on the page https://github.com/open-telemetry/opentelemetry-proto/releases

**Comment by tigrannajaryan** [comment]
I can change to a regular "release". Does anyone know if editing a release has any implications other than how it is labeled?
