### ISSUE TITLE
Rename proto/trace -> proto/traces

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-proto#176]
The other dirs are named `logs` and `metrics`, perhaps we can be consistent in naming?

**Comment by tigrannajaryan** [comment]
I agree. Once renamed we will need to update Collector too.

**Comment by bogdandrutu** [comment]
This is backwards compatible so we can do it. Better now than later

**Comment by mtwo** [comment]
@andrewhsu @bogdandrutu @carlosalberto given today's discussion, I assume that we're closing this? I don't have permissions to close it.

**Comment by tigrannajaryan** [comment]
In spec discussion we decided that since there is no good way to make the renaming everywhere we will not do the renaming at all.
