### ISSUE TITLE
Is knowing that a Histogram/Summary sum is monotonic important?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-proto#187]
Currently there is a TODO in the metrics proto that needs a decision:
> // TODO: Decide if knowing that the Sum is monotonic is important or not

**Comment by hdost** [comment]
This looks as if in the v1 of the protospec that this comment is gone which makes me think that this has been decided?

**Comment by bogdandrutu** [comment]
@jmacd I think we need this for the Histogram (probably for Summary as well), because currently OpenMetrics requires us to not send the Sum if values can be negative. We may want to discuss this in the Prometheus wg.

**Comment by jsuereth** [comment]
@bogdandrutu Can you comment on (a) if this is still an issue given the TODO is now gone and (b) how we resolve it.


Proposal from DataModel SiG:

- For OM / Prometheus export, ignore SUM if there are negative bucket values.

**Comment by bogdandrutu** [comment]
@jsuereth that is not 100% correct for the export. Reason is that I may not have a negative bucket defined but I may still have negative measurements, so the sum may still not be a Counter.

**Comment by jsuereth** [comment]
We discussed this in the DataModel SiG.

- For now sums will be exported as Counters (high compatibility with prometheus)
- We'd like to allow the use case of negative values in Histograms.
- We think we can provide some kind of semantic hint/detail outlining this scenario in the future in a non-breaking way.
  e.g. a `is_non_monotonic` boolean field that defaults to false.
