### ISSUE TITLE
Remove usage of TruncatableString

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-proto#19]
Initially TruncatableString was added in the OpenCensus to allow implementations to truncate strings at certain sizes if they exceed a certain limit.

This was actually never implemented or requested (there were clear requests for dropping events and attributes for long living Spans like for streaming RPCs).

I would suggest that we remove this:
pros:
  * less allocations when constructing the proto. this will improve the proto encode/decode.
  * less complicated JSON representation of the proto.
cons:
  * does not allow us to truncate strings and pass this information downstream.

cc @jmacd @iredelmeier @SergeyKanzhelev @tigrannajaryan

**Comment by c24t** [comment]
This seems like the right approach since we never implemented it in OC, and removing it doesn't prevent exporters from truncating strings on their way to the backend.

Would you expect to drop long strings instead of truncating them?

**Comment by jmacd** [comment]
+1
I would remove this.
One approach is to put information about the truncation into the string itself, like

"very long string... [checksum:length]"

but that can be done in a future revision, as long as the type is a simple string.

**Comment by bogdandrutu** [comment]
@jmacd I would not go that far to propose right now the solution for the long strings, but I agree what you said can be used for this case.
