### ISSUE TITLE
Check usage of int64 vs sfixed64 in metrics proto and uint64 vs fixed64

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-proto#211]

**Comment by tigrannajaryan** [comment]
Do you want to make sure we use them consistently or you want to check to see if there are any benefits and drawbacks?

They are all the same in-memory size, `int` versions may be more compact on the wire (for small values) and may be a tiny bit slower than `fixed` versions when marshaling/unmarshaling (likely negligible).

**Comment by bogdandrutu** [comment]
/private/var/folders/5c/5p_3jmvd6qx0rsvmb9j7c_s00000gn/T/___BenchmarkEncodeDecode_in_github_com_bogdandrutu_metrics_proto_benchmark__3_ -test.v -test.bench ^\QBenchmarkEncodeDecode\E$ -test.run ^$
goos: darwin
goarch: amd64
pkg: github.com/bogdandrutu/metrics-proto/benchmark
BenchmarkEncodeDecode
BenchmarkEncodeDecode/merged
BenchmarkEncodeDecode/merged-16         	   35745	     33669 ns/op	   30288 B/op	     523 allocs/op
BenchmarkEncodeDecode/mergedfixed
BenchmarkEncodeDecode/mergedfixed-16    	   36036	     33310 ns/op	   30416 B/op	     523 allocs/op
BenchmarkEncodeDecode/unmerged
BenchmarkEncodeDecode/unmerged-16       	   36104	     32878 ns/op	   29168 B/op	     523 allocs/op
BenchmarkEncodeDecode/unmergedfixed
BenchmarkEncodeDecode/unmergedfixed-16  	   36522	     32474 ns/op	   29296 B/op	     523 allocs/op
PASS

Process finished with exit code 0

**Comment by jmacd** [comment]
This was discussed and we did not find a lot of support.
