### ISSUE TITLE
Add explicit repeated <string, string> key value pairs to AnyValue

### ISSUE THREAD

**Issue by itamarkam** [open-telemetry/opentelemetry-proto#234]
The [body](https://github.com/open-telemetry/opentelemetry-proto/blob/8ab21e9da6246e465cd9d50d405561aedef31a1e/opentelemetry/proto/logs/v1/logs.proto#L107) of the OTLP log proto is an [AnyValue](https://github.com/open-telemetry/opentelemetry-proto/blob/8ab21e9da6246e465cd9d50d405561aedef31a1e/opentelemetry/proto/common/v1/common.proto#L27), which can be used for repeated key value pairs (using the KeyValueList type).
When used with string values, the proto looks like this:
```proto
body {  # AnyValue
  kvlist_value {  # KeyValueList
    values {  # KeyValue
      key: "key1"
      value {  # AnyValue
        string_value: "value1"
      }
    }
    values {  # KeyValue
      key: "key2"
      value {  # AnyValue
        string_value: "value2"
      }
    }
    ...
  }
}
```

The common proto already has a [StringKeyValue](https://github.com/open-telemetry/opentelemetry-proto/blob/8ab21e9da6246e465cd9d50d405561aedef31a1e/opentelemetry/proto/common/v1/common.proto#L52) message, which if used, would save one level of nesting for the string values and improve performance.
That is:
```proto
message StringKeyValueList {
  repeated StringKeyValue values = 1;
};

message AnyValue {
  oneof value {
    ...
    StringKeyValueList string_kvlist_value = 7;
  }
}
```

* The same might make sense for other value types, but strings are the heaviest performance-wise.

**Comment by tigrannajaryan** [comment]
The attributes of traces are already declared stable. It is highly desirable to keep attributes of logs uniform with attributes of traces. This proposal breaks the uniformness which is a significant downside. I do not see performance improvement as a sufficient arguments in favor of the change.

**Comment by tigrannajaryan** [comment]
Closing as "won't do", since it adds complexity, and can be confusing since there will be 2 ways to record map<string,string>. Can be reopened if we see this is a major performance bottleneck.
