### ISSUE TITLE
Please release 0.7.0 version with DoubleSummary support

### ISSUE THREAD

**Issue by gcacace** [open-telemetry/opentelemetry-proto#235]
In order to unblock https://github.com/open-telemetry/opentelemetry-java/pull/2027 we need the DoubleSummary version released (see commit https://github.com/open-telemetry/opentelemetry-proto/commit/8ab21e9da6246e465cd9d50d405561aedef31a1e).

**Comment by gcacace** [comment]
Hello, can we get some traction on this please?

**Comment by gcacace** [comment]
Hello,

It has been more than a month without any update. Is there anything that I can do in order to release this new version of the protocol?

**Comment by anuraaga** [comment]
@bogdandrutu @open-telemetry/specs-approvers We need some support here. Either proto should be released with some schedule (monthly?) or the releases should be removed completely in favor of a policy where each language manages the version independently from anything else. I guess the former is less fragile but currently I feel we lack an owner of proto releases.

**Comment by gcacace** [comment]
Hello,

Now it's been nearly 2 months waiting for a release of the proto version. Is there any way I can help with the release, then with the bump-up of its version on the java sdk?

**Comment by bogdandrutu** [comment]
@tigrannajaryan @carlosalberto @jmacd @yurishkuro @arminru @SergeyKanzhelev can you +1 this if you don't see any blocked and we can move forward with the release?

**Comment by bogdandrutu** [comment]
Done.

**Comment by tigrannajaryan** [comment]
@bogdandrutu I can see the v0.7.0 tag but not a Github release. Do you plan to add the release?
