### ISSUE TITLE
Extra metadata for OTLP exporter

### ISSUE THREAD

**Issue by gcacace** [open-telemetry/opentelemetry-proto#239]
Let's assume there is a use case where an Instrumentation library generates some [ResourceMetrics](https://github.com/open-telemetry/opentelemetry-proto/blob/f11e0538fd7dc30127ca6bfb2062e5d9f782b77b/opentelemetry/proto/metrics/v1/metrics.proto#L28).

I'm wondering if it make sense adding a sort of "Metadata" key-value field in the [InstrumentationLibrary](https://github.com/open-telemetry/opentelemetry-proto/blob/f11e0538fd7dc30127ca6bfb2062e5d9f782b77b/opentelemetry/proto/common/v1/common.proto#L74) data structure, so that would be possible decorating the transport message with additional info such as:
* hostname/IP of the host which generated the `ResourceMetrics`
* Cloud provider which generated the `ResourceMetrics`
* identifier of a configuration of the system which generated the `ResourceMetrics`
* any other key-value pair depending on the vendor of the system which generated the `ResourceMetrics`.

Without this field, the only place where any sort of arbitrary key-value pair can be stored is under the data-point `Labels`, which is not ideal since it gets mixed up with the domain of the specific metric, not the domain of the instrumentation library/system which produced and dispatched that metric.

**Comment by jkwatson** [comment]
Isn't this just the Resource?

**Comment by gcacace** [comment]
> Isn't this just the Resource?

Not if there is an intermediate service responsible for routing/dispatching/exporting those Resource metrics.

Isn't Resource something strictly related to the domain of the metric?

**Comment by tigrannajaryan** [comment]
It is not clear how the described "Metadata" is different from Resource.

**Comment by jkwatson** [comment]
@gcacace The Resource is associated with the entity emitting the telemetry signals. See here for the related semantic conventions, which might make things more clear:  https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/resource/semantic_conventions

**Comment by gcacace** [comment]
Gotcha. Thanks!
