### ISSUE TITLE
Release 0.7.0 was not released properly

### ISSUE THREAD

**Issue by gcacace** [open-telemetry/opentelemetry-proto#250]
0.7.0 doesn't show up as "latest release": https://github.com/open-telemetry/opentelemetry-proto/releases

**Comment by Oberon00** [comment]
It does show up, but it is only a tag, not a full GH release.

**Comment by bogdandrutu** [comment]
Done https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.7.0
