### ISSUE TITLE
Consider to remove IntExemplar and offer only DoubleExemplar (a.k.a Exemplar)

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-proto#256]
This decision was made in the initial beta release of the metrics, but after using this data model in the collector for some time, I came to the conclusion that they are a bit harmful (I have a bunch of places where I have to deal with conversion for this extra type).  By using only one `Exemplar` we may lose precision for the `value`, but how large should the value be to have this problem, based on the IEEE 754 the maximum value is ~2^53 (I found on a [stackoverflow thread](https://stackoverflow.com/questions/1848700/biggest-integer-that-can-be-stored-in-a-double#:~:text=The%20biggest%2Flargest%20integer%20that,It's%20represented%20exactly.) that the value seem to be 9007199254740992) to not lose precision at all. I think this is a reasonable compromise for usability.

The deprecation will work this way:
* Rename current DoubleExemplar to just Exemplar.
* Everywhere where we use IntExemplar deprecate that field and replace it with Exemplars.
* When receiving a deprecated `IntExemplar` field, receiver can convert it into the new `Exemplar` field, only operation needed is to convert the int64 value into double.
* In the collector we will do this in the OTLP receiver, and will remove access to the deprecated field.

/cc @jmacd @open-telemetry/specs-metrics-approvers

**Comment by jmacd** [comment]
Strong support, like #257.
