### ISSUE TITLE
Consider to remove IntHistogram and offer only DoubleHistogram (a.k.a Histogram)

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-proto#257]
This decision was made in the initial beta release of the metrics, but after using this data model in the collector for some time, I came to the conclusion that they are a bit harmful (I have a bunch of places where I have to deal with conversion for this extra type). By using only the `DoubleHistograms` we may lose precision for the `sum` and for the `value` in the Exemplar (see #256 for details about exemplar). Same argument as described in the Exemplar case can be applied for the `sum`, and we also can consider the fact that usually when exporting a Histogram users will often look at the percentiles which will be anyway approximations and precision will be lost there regardless of the `sum` being accurate.

We will keep the IntGuage/IntSum for special cases where people really care about precision for these large numbers.

The deprecation will work this way:
* Rename current `DoubleHistogram` to just `Histogram`.
* Deprecate IntDouble from the metric types we support.
* When receiving a deprecated `IntHistograms` type, the receiver can convert it into the new `Histogram`, only operation needed is to convert the int64 sum into double. Exemplars will be handled by #256.
* In the collector we will do this in the OTLP receiver, and will remove access to the deprecated field.

/cc @jmacd @open-telemetry/specs-metrics-approvers

**Comment by jmacd** [comment]
Strong support.

Can you strike this line?

> Deprecate IntDouble from the metric types we support.

It seems to conflict with

> We will keep the IntGuage/IntSum for special cases where people really care about precision for these large numbers.
