### ISSUE TITLE
Metric Service Discovery Specs

### ISSUE THREAD

**Issue by austince** [open-telemetry/opentelemetry-proto#263]
Hey all, I'm doing some research on service discovery for scraping metrics (like[ the ones natively supported in Prometheus](https://github.com/prometheus/prometheus/tree/master/discovery)). I'm wondering if there's been any work in open-telemetry to define a standard discovery protocol for metric scrape targets (and associated labels)? The protocol defined in [OTEPS](https://github.com/open-telemetry/oteps/blob/main/text/0035-opentelemetry-protocol.md) looks interesting, but leaves out discovery.

>  More significant changes must be explicitly defined as new optional capabilities in future RFCs. Such capabilities SHOULD be discovered by client and server implementations after establishing the underlying transport. The exact discovery mechanism SHOULD be described **in future RFCs** which define the new capabilities and typically can be implemented by making a discovery request/response message exchange from the client to server. The mandatory capabilities defined by this specification are implied and do not require a discovery. The implementation which supports a new, optional capability MUST adjust its behavior to match the expectation of a peer that does not support a particular capability.

Have I just missed it somewhere?

Thanks!

**Comment by jmacd** [comment]
@austince Yes!

See here:
https://github.com/open-telemetry/opentelemetry-specification/issues/1078#issuecomment-776334709
and 
https://github.com/open-telemetry/opentelemetry-specification/issues/1298#issuecomment-775749864

As you'll see, this is a current topic. I'm trying to catch up with rumored parallel conversations in the OTel Logging group that is discussing how we log about resources, which feels related.

**Comment by austince** [comment]
This seems like the wrong repo for this issue, but thanks for pointing me to those conversations! I'll be actively following if you all decide to adopt "service discovery" into your domain (🤞🏼).
