### ISSUE TITLE
Add a repository description on GitHub

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-proto#265]
This repository has no description on GitHub. I suggest "Protobuf definitions for the OpenTelemetry protocol (OTLP)". Or we could use what's written in the README today "Language Independent Interface Types For OpenTelemetry", although I like that less.

**Comment by tigrannajaryan** [comment]
I went with your first suggestion. Closing. Anyone, feel free to reopen if you think the description should be different.

**Comment by Oberon00** [comment]
Thank you!
