### ISSUE TITLE
Add min and max values to the histogram data points

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-proto#266]
Today, OpenTelemetry doesn't report min and max values collected for a histogram data point and is breaking the capability to query absolute min and max values from a time series. We propose to add min and max values to the histogram data types. When users set boundaries explicitly, not reporting precise min and max doesn't allow them to see whether their bucket boundaries are well-chosen and precisely set.

Here are some use cases where being able to query absolute min and max values from a series is critical:

* In latency analysis, the bucket boundaries often starts at 0 even though the smallest latency will never be 0. Being able to see the absolute minimum allows users to evaluate the minimum value. This sometimes helps users to find bugs! For example, if your min never went below 40ms for a case where theoretical latency could be 20 ms, it may help you to identify something went wrong.
* Being able to see the max allow users to see how far it is from the 95th/99th percentile. Seldom spikes can add noise to the highest buckets, reporting maximum allows users to adjust bucket boundaries if needed. 
* Outliers are easier to detect with max. For example 1 TB of nearly full disk usage on a few machines will be invisible in the aggregate buckets but are important to identity.
* When doing trend analysis over time, min and max (when collected) are easy to query and allows you to precisely see the boundaries of the population.

**Comment by jmacd** [comment]
Following the discussion on Tuesday, we still have technical details to resolve before we can add min/max to the protocol. The discussion has circled around these points:

1. When temporality is cumulative, the implied meaning for min/max is the min and max over the entire series, which is not what's actually desired
2. When temporality is delta, the implied meaning is :100:, we can precisely encode the min and max over short windows of time.

Looking toward Prometheus, there's at least one more concern. Data pulled from a /metrics endpoint has no (stateless) way to encode a delta, but it is equally undesirable to report the lifetime min and max of a series. Therefore, Prometheus Summary data types expose the min and max value (i.e., φ = 0 and φ = 1) over a fixed window of time.

I believe the best outcome for a Prometheus user will be to emulate the behavior of the Summary data type's min and max fields for OTLP Histograms. This statement is practically the only option when OTLP's aggregation temporality is cumulative.

For OTLP delta aggregation temporality, we have two options.

The first option is for delta to behave exactly as cumulative temporality would. This allows change-of-temporality to be considered a true no-op for histograms.

The second option is for delta to output min and max precisely, meaning to report actual min/max values over short time windows.

I have a slight preference here, but I think both behaviors should be considered valid.

**Comment by jmacd** [comment]
Please review #279.
