### ISSUE TITLE
go get github.com/open-telemetry/opentelemetry-proto/gen/go/collector/trace/v1 error

### ISSUE THREAD

**Issue by DanTulovsky** [open-telemetry/opentelemetry-proto#267]
Hi... I am trying to 
`import "https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/collector/trace/v1/trace_service.proto"` into a go program...

but go get fails with:

```
% go get github.com/open-telemetry/opentelemetry-proto/gen/go/collector/trace/v1                      
go get: module github.com/open-telemetry/opentelemetry-proto@upgrade found (v0.7.0), but does not contain package github.com/open-telemetry/opentelemetry-proto/gen/go/collector/trace/v1
```
Is this the right package to use?

Thank you
Dan

**Comment by bogdandrutu** [comment]
See https://github.com/open-telemetry/opentelemetry-proto-go where go community wants to offer them.

**Comment by bogdandrutu** [comment]
So the import you have is outdated and you should avoid that :)

**Comment by DanTulovsky** [comment]
Thank you, but that one doesn't work either.  Or is it not ready yet?  If so, is there a version I can use today?  My use case is that I send traces from otel-collector to kafka, and then have a subscriber listening to that which needs to deserialize the proto.

```
% go get go.opentelemetry.io/proto/otlp/trace/v1                                     
go get: module go.opentelemetry.io@upgrade found (v0.1.0), but does not contain package go.opentelemetry.io/proto/otlp/trace/v1
```

**Comment by tigrannajaryan** [comment]
@DanTulovsky https://github.com/open-telemetry/opentelemetry-proto-go is not ready yet. You will need to generate your own Go Protobufs from proto files for now.
