### ISSUE TITLE
Decide how to handle 64 bit integers in JSON encoding

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-proto#268]
According to JSON [RFC7159](https://tools.ietf.org/html/rfc7159#section-6) 64 bit numbers are not interoperable (outside of the `[-(2**53)+1, (2**53)-1]`  range.

Our timestamps are 64 bit nanosecond. We need to decide how to represent them. This also applies to any other 64 bit attribute value.

Go Protobuf JSON implementation seems to be happy with 64 bit integers but other implementations may not (particularly Javascript most likely will fail).

**Comment by mtestrot** [comment]
I raised this issue in a discussion on slack. The protobuf JSON mapping uses decimal strings like "1586960586000001001" to represent 64 bit numbers. cf. https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by jsuereth** [comment]
I think the protobuf support is likely the best option here:

1. You won't get loss-of-precision going through JavaScript (i.e. something that only parses JSON and fires it back is unlikely to break the number)
2. Likely JavaScript will have to use custom-handlers/types for int64 (or special `Number.isSafeInteger` fun)
3. Efficiency wise, in JSON it's only an additional two characters over what sending a number would be.

Note: This stackoverflow answer has a lot of good options/discussion: https://stackoverflow.com/questions/209869/what-is-the-accepted-way-to-send-64-bit-values-over-json

**Comment by mtestrot** [comment]
[RFC3339 ](https://tools.ietf.org/html/rfc3339) might be another viable option. It's very common for timestamps in JSON. And also used by [SYSLOG](https://tools.ietf.org/html/rfc5424#section-6.2.3). Furthermore it is readable by humans if you ever encounter logs in raw JSON format for example files.

**Comment by tigrannajaryan** [comment]
I looked into this. I think we should go with stringified number for the following reasons:
- It retains human readability virtually the same as we had before.
- Serialization performance/efficiency is virtually identical too, the difference is insignificant.
- It already works out-of-the box with Go's and Gogo's JSONProtobuf implementation, so there is nothing to do in the Collector or in Go SDK to support this.Go proto accepts both regular numbers and stringified numbers as valid values when decoding and stringifies when encoding, which is exactly what we want.

I am going to submit a PR against spec repo that clarifies this.
