### ISSUE TITLE
Update CHANGELOG.md in this repository

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-proto#271]
The CHANGELOG.md in this repository is not up to date and is not useful. I would say it's so incomplete that we should remove it, except that I think we should be updating the changelog when we make changes, and I believe it would be best if we created a retroactive changelog going back to v0.5.

**Comment by hdost** [comment]
This could be used as a good template: https://github.com/open-telemetry/opentelemetry-go/blob/main/CHANGELOG.md

**Comment by hdost** [comment]
Pushed an initial draft. Let me know what you think.

**Comment by jmacd** [comment]
Fixed by #276.
