### ISSUE TITLE
metrics: Meta issue about Data Model Stability Guarantees

### ISSUE THREAD

**Issue by hdost** [open-telemetry/opentelemetry-proto#275]
There are a couple of issues which are looking at breaking changes.

According to the [README.md](https://github.com/open-telemetry/opentelemetry-proto#maturity-level) right now. Metrics is considered _Beta_. However, as part of the [0.5.0 release](https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.5.0) there is a mention:
> This is a Release Candidate to declare Metrics part of the protocol **Stable**.

I believe from what I understand that it should still be considered _Beta_ given it's state. And the fact that only as of 0.7.0 was it even marked as _Beta_

Related Change Propositions:
#257 
#264 
#272 

As mentioned in https://github.com/open-telemetry/opentelemetry-proto/issues/264#issuecomment-791629884 we should try to make the transition smooth.

Taking a cursory look at the release history it looks like the last breaking change release was made 2020-08-31 in the form of release 0.5.0. So according to the [maturity matrix](https://github.com/open-telemetry/community/blob/47813530864b9fe5a5146f466a58bd2bb94edc72/maturity-matrix.yaml#L70) we are free to make a release which is not backwards compatible for metrics when we want.

My proposal would be: 

1. Add target types and deprecations to the the protocol
2. Release the "compatible" pre-release version 0.8.0. 
3. Incorporate the incompatible changes to the protocol.
4. Release the "incompatible" version whether that be 0.9.0 or which ever.  And this could be within a few days of each other possibly.

This change would also model for metrics to actually be _Stable_ according to the maturity matrix.

If something like this doesn't occur there is a strong risk of slippage on the whole metric roadmap. Which wouldn't necessarily be the end of the world, but estimates might need to be re-considered.

**Comment by hdost** [comment]
I also discovered (#269) PR which changes the name of Summary. This is something that would techncially break compatibility. Likely if we want to follow the above proposal we should consider reverting it before Step 2. Or more than likely re-add it and have the plain summary. The `DoubleSummary` should be marked deprecated, and then for the case of Step 3. it could then be removed.

**Comment by hdost** [comment]
cc: @jmacd , @bogdandrutu

**Comment by jmacd** [comment]
@hdost Acknowledging your point, we have to be careful how we describe these changes before the next release. Also we did not write a Changelog entry in #270, which led me back to this issue because I'm not sure how to classify the change. It's partly breaking (remove IntHistogram) and partly non-breaking (just a rename) -- because we have not declared JSON stability.

**Comment by hdost** [comment]
👍🏼 I do remember that JSON stability wasn't set, but I wasn't sure how things affect on the Protobuf side.
