### ISSUE TITLE
Is it necessary to define receiver/processor/exporter/extension type enum?

### ISSUE THREAD

**Issue by tbmxp** [open-telemetry/opentelemetry-proto#277]
I'm trying to implement a configuration checkin/checkout between otel agent/collector and the back-end control center. To give a guarantee of the validation constraint for the collecting configuration defined by users, the protobuf seems good. For example, sometimes users may write a not existed processor name or the ones not built in the binary.

Is it necessary to define the enum in opentelemetry-proto? The agent/collector proto could import it, and the back-end control center use it to avoid the invalid configuration. (However, the concrete parameters of receiver/processor/exporter may has configuration error as well. But, for a large scaled distributed system, it's securer to avoid it AFAP.)

enum OTelReceiverType {
    OTLP = 0;
    OPENCENSUS = 1;
    JAEGER = 2;
    ZIPKIN = 3;
    PROMETHUES = 4;
}

message ReceiverConfig {
  OTelReceiverType receiver = 1;
  option map<string, MapVaule> params = 2;
}

**Comment by hdost** [comment]
How would custom Receivers be handled?

**Comment by tbmxp** [comment]
> How would custom Receivers be handled?

Yes, for the custom Receivers(Exporters/Processors), users should add the custom type enum by themselves. If the custom component has been contributed to the OTel repository, new type enum might be added meanwhile. Pipeline configuration could use the components name, so in my opinion, this issue is just for easier to use.
