### ISSUE TITLE
Avoid using gogoprotobuf for generation

### ISSUE THREAD

**Issue by johanbrandhorst** [open-telemetry/opentelemetry-proto#290]
In the same vein as https://github.com/open-telemetry/opentelemetry-go/issues/1393, it would be ideal if this repository didn't rely on gogoprotobuf as it's basically unmaintained.

**Comment by bogdandrutu** [comment]
This repository does not rely on gogoproto, we can build without that as well. This repository just defines the proto files

**Comment by johanbrandhorst** [comment]
Sorry if I was unclear, I was referring to the Makefile: https://github.com/open-telemetry/opentelemetry-proto/blob/4a2aefa60114914fa7f2acd40ab376c9fc1f1e19/Makefile#L64.

**Comment by tigrannajaryan** [comment]
Otel generally relies on Gogoproto (particularly Collector), and we don't know yet how what we will replace it with. For now it needs to stay, so I am closing this here. It will need to be solved in the Collector first.
