### ISSUE TITLE
Open PRs for new protobufs based on changes in this repo

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-proto#294]
I was thinking about how our SIG (opentelemetry-php) could get the newest protobufs without always having to generate them or check validity of the latest commit, and it got me to thinking -

Could we potentially have a github action in this repo that opens PRs when a new version of opentelemetry-proto is released?

This could ensure that each SIG has copies of the newest version of the proto, and it could be merged at the SIGs earliest convenience. 

Do y'all have thoughts on this?

**Comment by jsuereth** [comment]
I think there used to be protocol buffer generation in this repo for Go and it was removed here: https://github.com/open-telemetry/opentelemetry-proto/commit/6f6985e626954b224ca45f14786b7bcd51c11490

I think I understand the reasoning behind it (i.e. keeping the generated code up-to-date with latest protocol buffer libraries, as well as other Go-related protocol buffer ordeals).    I assume PHP has something like this: https://github.com/open-telemetry/opentelemetry-java/blob/main/proto/build.gradle.kts (download latest + generated code) ?

Is it worth discussing this in the maintainers meeting?

**Comment by tigrannajaryan** [comment]
This was discussed a few times and decided that generated code should not live in this repo and should be in separate repos. We already have https://github.com/open-telemetry/opentelemetry-proto-go and https://github.com/open-telemetry/opentelemetry-proto-java so I think it is now too late too change anything. Closing this issue.
