### ISSUE TITLE
Cannot distinguish Histogram's Sum field between 0 vs not assigned.

### ISSUE THREAD

**Issue by victlu** [open-telemetry/opentelemetry-proto#314]
proto3 does not support a has_*() method. Thus, code cannot detect the difference between a field that is not assigned vs a field that has a default value (i.e. 0).

Current spec for Histogram's Sum field has a note to not assign the field in some condition. This condition not detectable by code (i.e. Sum is assigned to zero).

```
  // Note: Sum should only be filled out when measuring non-negative discrete
  // events, and is assumed to be monotonic over the values of these events.
  // Negative events *can* be recorded, but sum should not be filled out when
  // doing so.  This is specifically to enforce compatibility w/ OpenMetrics,
  // see: https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#histogram
```

**Comment by victlu** [comment]
FYI: @jsuereth @bogdandrutu

**Comment by victlu** [comment]
It seems we need to deprecate the use of this field, and move to a newer Sum field where we can redefine the context. This may include...

- Using a flag as outlined in #309 
- Define a new default (i.e. -1, or NaN) to mean "not assigned"

**Comment by Blacksmoke16** [comment]
Related: https://chromium.googlesource.com/external/github.com/protocolbuffers/protobuf/+/refs/heads/master/docs/implementing_proto3_presence.md.

That flag is no longer required in version `>=3.15.0`

**Comment by bogdandrutu** [comment]
@jsuereth @jmacd this is now an issue for sum in the exponential histogram correct? https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L466
