### ISSUE TITLE
is `logs.proto` up-to-date?

### ISSUE THREAD

**Issue by errordeveloper** [open-telemetry/opentelemetry-proto#318]
I've looked at [`logs.proto`](https://github.com/open-telemetry/opentelemetry-proto/blob/f3b0ee0861d304f8f3126686ba9b01c106069cb0/opentelemetry/proto/logs/v1/logs.proto), and I'm not sure if it's up-to-date with [the data model spec](https://github.com/open-telemetry/opentelemetry-specification/blob/152a50ae95b61b0af47c2abfafd426fc7b58d118/specification/logs/data-model.md). To me it looks like the structure is very different, and what is in `logs.proto` right now is probably based on an earlier version of the spec, or am I completely  misunderstanding this?

**Comment by tigrannajaryan** [comment]
It should be up to date. What are the differences that you see?

**Comment by errordeveloper** [comment]
Firstly, `timestamp` vs `time_unix_nano`. Secondly,  `LogRecord` doesn't have `resource` field right next `attributes`, but instead its parent `ResourceLogs` structure has it along with `instrumentation_library_logs` filed that holds an array of `LogRecord`s.

I can see that the data model document suggests that JSON examples are not meant to be representative, but that just very unhelpful. I was expecting naming and structure to be consistent...

**Comment by tigrannajaryan** [comment]
> Firstly, `timestamp` vs `time_unix_nano`.

This is for historical reasons to be uniform with the naming of time fields in spans (e.g. `start_time_unix_nano`).

> Secondly, LogRecord doesn't have resource field right next attributes, but instead its parent ResourceLogs structure has it along with instrumentation_library_logs filed that holds an array of LogRecords.

This is expected. The log data model in the spec is a logical description of data, it does not require the physical formats to mirror the structure. Again, the separation into ResourceLogs/InstrumentationLibraryLogs/LogRecords is historical and is uniform for logs, traces and metrics.

>I can see that the data model document suggests that JSON examples are not meant to be representative, but that just very unhelpful. I was expecting naming and structure to be consistent...

OTLP/JSON is an open issue. The current format is completely unstable. Once we decide what the format is going to be we can update the data model document to reflect it in the example (but it will remain just an example).

We can update the data model document to make it less confusing but you are approaching this with a wrong assumption. The data model in the spec is not expected to mirror the OTLP Protobuf format. OTLP Protobuf format is merely one possible representation of log data as it is understood by OpenTelemetry. 

The data model document specifically mentions this:
>This document does not define the actual encoding and format of the log record representation. Format definitions will be done in separate OTEPs (e.g. the log records may be represented as msgpack, JSON, Protocol Buffer messages, etc).

As another example of logical data model vs representation: the in-memory representations of log records in OpenTelemetry SDKs can be different than OTLP structure (and are in fact different for spans for example), although they correspond to the same logical data model.

If the wording in data model doc is unclear perhaps we need to make it clearer. Improvement suggestions are welcome.

**Comment by errordeveloper** [comment]
So if it said to be by design, I find it rather very unhelpful. As someone who is attempting to implement something based on this spec, I am failing to appreciate this kind of complexity. What is it for?

**Comment by errordeveloper** [comment]
> As another example of logical data model vs representation: the in-memory representations of log records in OpenTelemetry SDKs can be different than OTLP structure...

What is the reason behind this? I think it possess a usability issue.

**Comment by errordeveloper** [comment]
> If the wording in data model doc is unclear perhaps we need to make it clearer. Improvement suggestions are welcome.

If this is how things are ought to be, perhaps wording alone won't fix the issue. Maybe some kind of abstract schema definition language would help, something that would make it more explicit to the reader that the data model doc is not to be interpreted directly.

**Comment by tigrannajaryan** [comment]
> I find it rather very confusing. As someone who is attempting to implement something based on this spec, I am failing to appreciate this kind of complexity. What is this complexity for? It would be much easier to understand and implement the spec if it was illustrated using field names and structures that map directly to the current protobuf definitions. If the goal is to cover for future changes in the protobuf definitions or alternative encoding mechanisms, there ought to be several ways of achieving the same goals without confusing the readers.

Please feel free to submit an improvement PR or if you can't submit an issue against the spec so that someone else can have a look.



> > As another example of logical data model vs representation: the in-memory representations of log records in OpenTelemetry SDKs can be different than OTLP structure...
> 
> What is the reason behind this? I think it possess a usability issue.

In-memory representation may need to look differently to be optimized for speed or memory or even because the code dictates a different structure. See for example in-memory `Span` in Go SDK, which has fields that are different the Protobuf `Span` message: https://github.com/open-telemetry/opentelemetry-go/blob/12f737c7a563746b5ccb488832afee1e901d844c/sdk/trace/span.go#L102

**Comment by tigrannajaryan** [comment]
Closing since there was no follow up and it is not clear what is expected to be done. Feel free to reopen if there are specific suggestions.
