### ISSUE TITLE
Go: Value is exported with a non-exported type `isAnvValue_Value`

### ISSUE THREAD

**Issue by kentquirk** [open-telemetry/opentelemetry-proto#334]
I posted this report in the go repository, but it might not be the right place for it. Does it belong here instead?

https://github.com/open-telemetry/opentelemetry-proto-go/issues/25

**Comment by tigrannajaryan** [comment]
This is autogenerated code and cannot be altered. It is generated by Protobuf compiler. I agree it is an unnecessary limitation but there is nothing we can do here. You may want to file it as an issue with Protobuf folks.
