### ISSUE TITLE
Language Support: Rust

### ISSUE THREAD

**Issue by hdost** [open-telemetry/opentelemetry-proto#339]
Will rust support be added for this?

**Comment by tigrannajaryan** [comment]
Closing since https://github.com/protocolbuffers/protobuf/issues/6792 is still not done and out of our control. Feel free to re-open if anyone is willing spend the time and effort to solve this.

**Comment by alekspickle** [comment]
I mean, I could start to work on it but I certaintly not working in Google. :man_shrugging:
