### ISSUE TITLE
Trace id and Span id are shown as like C string literals.

### ISSUE THREAD

**Issue by KyongSik-Yoon** [open-telemetry/opentelemetry-proto#347]
I'm doing development opentelemetry collector exporter to my custom server.
Demo app is Jaeger hotrod. This app send tracing data to opentelementry-collector and this collector send to my custom server using GRPC with opentelemetry-proto.
(hotrod --> opentelemetry-collector --> via grpc --> my server)
When ResourceSpans are arrived I printing toString result and that's like below.

```
2021-12-31 11:15:38.468 UTC INFO trace_id: "\000\000\000\000\000\000\000\000h\215\\z,f+N"
span_id: "mg\035!\021\236\315\031"
parent_span_id: "h\215\\z,f+N"
name: "HTTP GET: /route"
start_time_unix_nano: 1640949104998102000
end_time_unix_nano: 1640949105061162000
status {
}
```

We can see trace_id, span_id, parent_span_id has C style literals.
I wonder what's the reason and can I possible convert to plain string value.
When I try call toStringUtf8 method of ByteString result value was very strange has special words. (ex) h�\z,f+N

**Comment by tigrannajaryan** [comment]
I do not think the issue belongs to this repository. We don't know how your server prints ResourceSpans and I don't see how we could diagnose this from our end with the information you provided.

If you suspect the Collector is doing something wrong with traceid/spand id you can submit an issue in the Collector repo, but make sure to provide reproduction details - what you have here is not enough. If you want to confirm what the trace id/span id look like in the Collector you can use the [logging](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/loggingexporter) exporter.
