### ISSUE TITLE
Add support for buf

### ISSUE THREAD

**Issue by remyleone** [open-telemetry/opentelemetry-proto#349]
[Buf](https://buf.build/) is a command-line tool that can create a compiled version of a protobuf set of files. This compiled schema can be shared on a [Buf Schema Registry](https://buf.build/product/bsr/) (BSR). By doing so, it becomes easier to manage large protobuf projects and their dependencies. A user could import the protobuf of the opentelemetry by declaring it in a buf configuration file and buf would make sure that the right version of the protobuf are downloaded and used at compile time.

Adding support for Buf would mean:
- Being able to compile the opentelemetry protobuf files to an image.
- Pushing this image to a registry with a well-recognized name `buf.build/opentelemetry/opentelemetry`.
- Enabling the GitHub action that performs this action automatically when pushing new commits are pushed to main.

**Comment by bogdandrutu** [comment]
Sounds interesting. Can we get at least 1-2 users of this to +1 so we understand why we pay the maintenance cost?

**Comment by shaxbee** [comment]
It will make it much easier to consume opentelemetry-proto as dependency as well :-)

**Comment by SergeyKanzhelev** [comment]
See comment here: https://github.com/open-telemetry/opentelemetry-proto/pull/348#issuecomment-1011426858 Please re-open if this is still needed.
