### ISSUE TITLE
Go proto import paths do not match actual import paths

### ISSUE THREAD

**Issue by v3n** [open-telemetry/opentelemetry-proto#353]
The [go.mod for the go-proto](https://github.com/open-telemetry/opentelemetry-proto-go/blob/main/go.mod) repository declares the module import to be go.opentelemetry.io/proto.

The `go_package` directive declares them to be at github.com/open-telemetry/opentelemetry-proto/gen/go/collector/trace/v1; which doesn't exist via `go get`.

**Comment by bogdandrutu** [comment]
The `go_package` is declared here to ensure that generated go files in the CI of this repo "compile". The `go_package` flag is a problem when you have different places to declare protos and generate them, so not sure how this can be fixed.

**Comment by gordallott** [comment]
the CI might be validating that the go files generated from the proto here are compilable, but the proto and the go files generated from it are functionally useless to anyone else as long as this issue exists. It wasn't an issue before as the generated go files were comitted to this repo and thus anyone depending on these proto files had somewhere to `go get` from

I would heavily suggest comitting the go files somewhere, either in this repo or somewhere else, and having the `go_package` directive point there 

otherwise the proto files are entirely useless in the golang world

**Comment by tigrannajaryan** [comment]
There is now canonical https://github.com/open-telemetry/opentelemetry-proto-go, we could point the Go package in proto files to that.

Either way you can just use https://github.com/open-telemetry/opentelemetry-proto-go directly as a dependency. It contains the generated files.

**Comment by v3n** [comment]
> The go_package is declared here to ensure that generated go files in the CI of this repo "compile". The go_package flag is a problem when you have different places to declare protos and generate them, so not sure how this can be fixed.

The protoc best practices expectation is that the `go_package` directive is the import path for those files (and they compile without changes).

> Either way you can just use https://github.com/open-telemetry/opentelemetry-proto-go directly as a dependency. It contains the generated files.

This still breaks, if I were to write a protobuf file that included any of the OpenTelemetry messages, the generated Go file would not compile since the package declared via `go_package` does not exist.

This also requires a bunch of fragile resolution steps when using Bazel + [Gazelle](https://github.com/bazelbuild/bazel-gazelle) as the both tools expect the paths to match up per Google's protobuf guidelines.

> There is now canonical https://github.com/open-telemetry/opentelemetry-proto-go, we could point the Go package in proto files to that.

This would be appropriate.

I highly recommend taking a look how Envoy's [protobuf API tree](https://github.com/envoyproxy/envoy/tree/main/api) is structure along with their [generated files repo](https://github.com/envoyproxy/go-control-plane). Google's `googleapis` Github organization is another good example.

**Comment by tigrannajaryan** [comment]
PR submitted https://github.com/open-telemetry/opentelemetry-proto/pull/360

**Comment by v3n** [comment]
Thanks for the quick turnaround y'all!
