### ISSUE TITLE
Generating C# from protos results in uncompilable code

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-proto#355]
The following results in a property name `Equals` which conflicts with the [`Equals`](https://docs.microsoft.com/en-us/dotnet/api/system.object.equals) method present on the base type that all types in C# derive from.

https://github.com/open-telemetry/opentelemetry-proto/blob/92d15b79b5f24c711cf2c00fee366904069bcb6b/opentelemetry/proto/metrics/experimental/metrics_config_service.proto#L71-L76

Can `equals` be renamed to `equal_to` or something to that affect?

**Comment by tigrannajaryan** [comment]
I think it is OK to do it. This is in the experimental part, we are free to make changes there.

**Comment by alanwest** [comment]
Thanks, resolved by #359
