### ISSUE TITLE
Link in release note is incorrect

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-proto#374]
The "this compare" link in this [release](https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.15.0) is inverted. Instead of:
https://github.com/open-telemetry/opentelemetry-proto/compare/v0.15.0...v0.14.0

It should be

https://github.com/open-telemetry/opentelemetry-proto/compare/v0.14.0...v0.15.0

**Comment by cbandy** [comment]
The links for 0.12.0, 0.13.0, and 0.14.0 are also inverted.

### Incorrect:
https://github.com/open-telemetry/opentelemetry-proto/blob/3c2915c01a9fb37abfc0415ec71247c4978386b0/CHANGELOG.md?plain=1#L25
https://github.com/open-telemetry/opentelemetry-proto/blob/3c2915c01a9fb37abfc0415ec71247c4978386b0/CHANGELOG.md?plain=1#L37
https://github.com/open-telemetry/opentelemetry-proto/blob/3c2915c01a9fb37abfc0415ec71247c4978386b0/CHANGELOG.md?plain=1#L45
https://github.com/open-telemetry/opentelemetry-proto/blob/3c2915c01a9fb37abfc0415ec71247c4978386b0/CHANGELOG.md?plain=1#L65

### Correct:
https://github.com/open-telemetry/opentelemetry-proto/blob/3c2915c01a9fb37abfc0415ec71247c4978386b0/CHANGELOG.md?plain=1#L78
