### ISSUE TITLE
Where I can find npm publication of compiled files

### ISSUE THREAD

**Issue by medikoo** [open-telemetry/opentelemetry-proto#379]
Documentation states:

> The compiled files are published to central repositories (Maven, NPM...) from OpenTelemetry client libraries.

Question is where are "OpenTelemetry client libraries" (?) There's no link provided

What are the NPM package names, at which those files are published (?)

**Comment by jamesdesmond** [comment]
This is similar to an issue I filed earlier: https://github.com/open-telemetry/opentelemetry-proto/issues/365

**Comment by medikoo** [comment]
@jamesdesmond Thanks for pointing. Still, that one was closed without addressing.

Is there any chance to have documentation updated so it points us to the right places?

**Comment by tigrannajaryan** [comment]
@open-telemetry/javascript-maintainers if the NPM packages exist I can update this repo to link to it. If they don't exist we should probably remove the reference to NPM.

**Comment by dyladan** [comment]
They don't exist
