### ISSUE TITLE
Consider moving start_time_unixnano to timeseries

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-proto#38]
start_time_unixnano is likely going to be the same for all data point in timeseries. Moving this to timeseries message instead of putting it in the value (as it is now) will be a space and speed optimization.

**Comment by jmacd** [comment]
I've wondered about this too. If you were collecting metrics over a large interval, especially for measure metrics, you would probably want individual timestamps, which is what OpenMetrics has specified. However it's wasteful in an SDK where you expect to export frequently. I'd leave both as options. OpenMetrics allows the timestamp to be omitted, in which case the backend uses its own, but I would prefer it to be an explicit field associated with the whole report.

**Comment by tigrannajaryan** [comment]
@bogdandrutu any thoughts on this? You mentioned we never even reset the timestamps in the SDK currently.

**Comment by SergeyKanzhelev** [comment]
If we will want to have this field on time series later we can always add it, correct? Should we close this issue for now?

**Comment by tigrannajaryan** [comment]
Yes, let's close this for now.
