### ISSUE TITLE
InstrumentationScope with Attributes

### ISSUE THREAD

**Issue by SWYZZWH** [open-telemetry/opentelemetry-proto#386]
I'm wondering whether InstrumentationScope can add an Attributes field. InstrumentationScope is unable to store rich meta-information now with "name" and "version" fields. In my case, metrics with the same attributes will be gathered in one InstrumentationScope. Moving these attributes to InstrumentationScope will dramatically improve the efficiency of memory, transmission, and storage.

**Comment by arminru** [comment]
Hi @SWYZZWH!
In https://github.com/open-telemetry/oteps/pull/201 we are already discussing a proposal for this. Please bring up your ideas there so we have the discussion all in one place.
Also, the existing [Resource](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md) might work for you.
Thank you!

**Comment by tigrannajaryan** [comment]
@SWYZZWH it would be very useful if you could describe your use case for InstrumentationScope attributes in more details as a comment at https://github.com/open-telemetry/oteps/pull/201
