### ISSUE TITLE
Release a version with min/max on histogram

### ISSUE THREAD

**Issue by shakuzen** [open-telemetry/opentelemetry-proto#387]
Min/max was added in https://github.com/open-telemetry/opentelemetry-proto/pull/279 after the 0.16.0 release, which is, at the time of opening this issue, the latest release. Could a new release be made so that consumers of this project can use the min/max that was added?

**Comment by arminru** [comment]
@shakuzen There you go: https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.17.0
