### ISSUE TITLE
optional keyword in sum field breaks build on Ubuntu 20.04

### ISSUE THREAD

**Issue by eata7** [open-telemetry/opentelemetry-proto#394]
`--experimental_allow_proto3_optional` flag is since protoc version 3.12.0 but Ubuntu focal focus installs 3.6.1 with packages. optional keyword breaks our build now. Is it possible to use `oneof` instead?

**Comment by tigrannajaryan** [comment]
Do you have to use the old version? Can you use `otel/build-protobuf` docker image for generation instead?

**Comment by tigrannajaryan** [comment]
I am not sure. It may be best to ask in https://github.com/open-telemetry/opentelemetry-cpp repo.

**Comment by sirzooro** [comment]
This also breaks build on RedHat 8 and CentOS 8, both use protobuf 3.5.0. It is very unlikely that RedHat would pull in newer protobuf into RedHat 8, they usually backport bug and security fixes only.

**Comment by tigrannajaryan** [comment]
Closing since it is not clear how to fix this. If anyone knows how to do it and is able to help please reopen.

**Comment by Falmarri** [comment]
This is super frustrating. This prevents building on ubuntu focal as well. And the optional keywords are only used for metrics. So even if you don't use metrics and only want tracing, you can't.

I've worked around this by just doing this

```
    && sed -i 's/^\(\s*\)optional /\1/g' ../third_party/opentelemetry-proto/opentelemetry/proto/metrics/v1/metrics.proto \
    && sed -i 's/"--experimental_allow_proto3_optional"//g' ../cmake/opentelemetry-proto.cmake \
```

In my builds. Since I'm not actually using the metrics for my c++ code. But this is pretty crazy to prevent building on even fully supported OSes. Who do you think is going to want to be running tracing, especially c++ tracing? It's going to be large enterprises. Many of which are going to be on very old versions.

**Comment by sirzooro** [comment]
> But this is pretty crazy to prevent building on even fully supported OSes. Who do you think is going to want to be running tracing, especially c++ tracing? It's going to be large enterprises. Many of which are going to be on very old versions.

Good point. Startups also may use tracing, but they usually prefer other languages. C++ tracing would be used mostly for old legacy system which nowadays may be ported to the cloud. Even if they are on RedHat 8 which is still supported today, they still have old protobuf by default - RedHat gets latest packages when they prepare new X.0 release (e.g. 8.0), and then merge bug fixes only from upstream for subsequent X.Y releases (8.1, 8.2, ...).

**Comment by Falmarri** [comment]
Especially because so much work was put into the C++ code to support all the way back to C++11. Anyone on C++11 isn't going to be using basically the latest protobuf library, which is pretty much what's required

**Comment by tigrannajaryan** [comment]
We do not plan to reopen this issue. The field definition is now part of the Stable release and our stability guarantees prevent changes to field qualifiers.

The workaround is to patch the proto files as @Falmarri [posted above](https://github.com/open-telemetry/opentelemetry-proto/issues/394#issuecomment-1676103852).

If there is a broad interest in the patched version please feel free to fork the repo and maintain the patch.

We can also accept a PR that documents the solution (how to patch) in the proto file comments.
