### ISSUE TITLE
Metrics proto didn't support back-compatibility when metric double value is 0.0 (v0.28->v0.31)

### ISSUE THREAD

**Issue by CatherineF-dev** [open-telemetry/opentelemetry-proto#398]
- What happened (deserialized value is nil):
  1. serialize: Gauge metric (value=0.0) ---> bytes, using [v0.28](https://github.com/open-telemetry/opentelemetry-proto/blob/8ab21e9da6246e465cd9d50d405561aedef31a1e/opentelemetry/proto/metrics/v1/metrics.proto)
  2. deserialize: bytes ---> nil, using [v0.31](https://github.com/open-telemetry/opentelemetry-proto/blob/e62655731f02540dd57785f1e7d0126ee9e1bcc4/opentelemetry/proto/metrics/v1/metrics.proto)

- What expected:
The metric value is not nil in step 2.  It's back-compatibility when metric value=0.1, 1.0 or 0 (int).

- Reproduce: 
https://github.com/CatherineF-dev/opentelemetry-collector/tree/master/processor/protoprocessor

- Guess:
[`one of`](https://developers.google.com/protocol-buffers/docs/proto3#backwards-compatibility_issues) doesn't support back-compatibility when value=0.0 https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L403-L406

**Comment by CatherineF-dev** [comment]
cc @bogdandrutu

**Comment by tigrannajaryan** [comment]
> * serialize: Gauge metric (value=0) ---> bytes, using [v0.28](https://github.com/open-telemetry/opentelemetry-proto/blob/8ab21e9da6246e465cd9d50d405561aedef31a1e/opentelemetry/proto/metrics/v1/metrics.proto)
> * deserialize: bytes ---> nil, using [v0.31](https://github.com/open-telemetry/opentelemetry-proto/blob/e62655731f02540dd57785f1e7d0126ee9e1bcc4/opentelemetry/proto/metrics/v1/metrics.proto)

I am confused by version numbers referenced here. The latest proto version is 0.18.0. Where do v0.28 and v0.31 come from?

**Comment by CatherineF-dev** [comment]
Sry for the confusion. The version is the version of openTelemetry collector.

**Comment by CatherineF-dev** [comment]
It seems 0 is not represented directly in proto bytes.  It's weird that collector version v0.28 can deserialize that double 0.0, while collector version v0.31 couldn't.

Used https://github.com/mildsunrise/protobuf-inspector to parse proto bytes (collector version v0.28)

```
# double 0
# []byte{10, 86, 10, 0, 18, 82, 10, 0, 18, 78, 10, 4, 116, 101, 115, 116, *42*, 70, 10, 68, 10, 23, 10, 6, 108, 97, 98, 101, 108, 49, 18, 13, 108, 97, 98, 101, 108, 49, 45, 118, 97, 108, 117, 101, 49, 10, 23, 10, 6, 108, 97, 98, 101, 108, 50, 18, 13, 108, 97, 98, 101, 108, 50, 45, 118, 97, 108, 117, 101, 49, 17, 0, 46, 153, 197, 228, 153, 201, 22, 25, 0, 46, 153, 197, 228, 153, 201, 22}

message:
    1 <chunk> = message:
        1 <chunk> = empty chunk
        2 <chunk> = message:
            1 <chunk> = empty chunk
            2 <chunk> = message:
                1 <chunk> = "test"
                5 <chunk> = message:
                    1 <chunk> = message:
                        1 <chunk> = message:
                            1 <chunk> = "label1"
                            2 <chunk> = "label1-value1"
                        1 <chunk> = message:
                            1 <chunk> = "label2"
                            2 <chunk> = "label2-value1"
                        2 <64bit> = 0x16C999E4C5992E00 / 1642012747000000000 / 6.6891710e-199
                        3 <64bit> = 0x16C999E4C5992E00 / 1642012747000000000 / 6.6891710e-199
# double 1
message:
    1 <chunk> = message:
        1 <chunk> = empty chunk
        2 <chunk> = message:
            1 <chunk> = empty chunk
            2 <chunk> = message:
                1 <chunk> = "test"
                5 <chunk> = message:
                    1 <chunk> = message:
                        1 <chunk> = message:
                            1 <chunk> = "label1"
                            2 <chunk> = "label1-value1"
                        1 <chunk> = message:
                            1 <chunk> = "label2"
                            2 <chunk> = "label2-value1"
                        2 <64bit> = 0x16C999E4C5992E00 / 1642012747000000000 / 6.6891710e-199
                        3 <64bit> = 0x16C999E4C5992E00 / 1642012747000000000 / 6.6891710e-199
                        4 <64bit> = 0x3FF0000000000000 / 4607182418800017408 / 1.0000000
# int 0
# []byte{10, 86, 10, 0, 18, 82, 10, 0, 18, 78, 10, 4, 116, 101, 115, 116, *34*, 70, 10, 68, 10, 23, 10, 6, 108, 97, 98, 101, 108, 49, 18, 13, 108, 97, 98, 101, 108, 49, 45, 118, 97, 108, 117, 101, 49, 10, 23, 10, 6, 108, 97, 98, 101, 108, 50, 18, 13, 108, 97, 98, 101, 108, 50, 45, 118, 97, 108, 117, 101, 49, 17, 0, 46, 153, 197, 228, 153, 201, 22, 25, 0, 46, 153, 197, 228, 153, 201, 22}

message:
    1 <chunk> = message:
        1 <chunk> = empty chunk
        2 <chunk> = message:
            1 <chunk> = empty chunk
            2 <chunk> = message:
                1 <chunk> = "test"
                4 <chunk> = message:
                    1 <chunk> = message:
                        1 <chunk> = message:
                            1 <chunk> = "label1"
                            2 <chunk> = "label1-value1"
                        1 <chunk> = message:
                            1 <chunk> = "label2"
                            2 <chunk> = "label2-value1"
                        2 <64bit> = 0x16C999E4C5992E00 / 1642012747000000000 / 6.6891710e-199
                        3 <64bit> = 0x16C999E4C5992E00 / 1642012747000000000 / 6.6891710e-199


# int 1
message:
    1 <chunk> = message:
        1 <chunk> = empty chunk
        2 <chunk> = message:
            1 <chunk> = empty chunk
            2 <chunk> = message:
                1 <chunk> = "test"
                4 <chunk> = message:
                    1 <chunk> = message:
                        1 <chunk> = message:
                            1 <chunk> = "label1"
                            2 <chunk> = "label1-value1"
                        1 <chunk> = message:
                            1 <chunk> = "label2"
                            2 <chunk> = "label2-value1"
                        2 <64bit> = 0x16C999E4C5992E00 / 1642012747000000000 / 6.6891710e-199
                        3 <64bit> = 0x16C999E4C5992E00 / 1642012747000000000 / 6.6891710e-199
                        4 <64bit> = 0x0000000000000001 / 1 / 4.9406565e-324
```

**Comment by CatherineF-dev** [comment]
Yes, it's also related to how `0` is represented in protobuffer. Since only 0.0 didn't support back-compatibility where other double values supported.


- In OTLP 0.7.0, protobuffer doesn't store value 0 in bytes representation. And OTLP 0.7.0 uses [default value 0](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.28.0/internal/data/protogen/metrics/v1/metrics.pb.go#L4277).

- In OTLP 0.8.0, protobuffer stores value 0 in bytes representation (use `oneof`).

So, when upgrading from OTLP 0.7.0 to OTLP 0.8.0, value 0 or 0.0 is not stored and relies on default value. 
For 0, it will in in intGauge and have default value 0. 
For 0.0, it will be in Gauge and doesn't have default value, which ends with nil value.


```
# OTLP 0.7.0: protobuffer didn't store 0 in bytes representation. 
message:
    1 <chunk> = message:
        1 <chunk> = empty chunk
        2 <chunk> = message:
            1 <chunk> = empty chunk
            2 <chunk> = message:
                1 <chunk> = "test"
                5 <chunk> = message:
                    1 <chunk> = message:
                        1 <chunk> = message:
                            1 <chunk> = "label1"
                            2 <chunk> = "label1-value1"
                        1 <chunk> = message:
                            1 <chunk> = "label2"
                            2 <chunk> = "label2-value1"
                        2 <64bit> = 0x16C999E4C5992E00 / 1642012747000000000 / 6.6891710e-199
                        3 <64bit> = 0x16C999E4C5992E00 / 1642012747000000000 / 6.6891710e-199
```



```
# OTLP 0.8.0: protobuffer stored 0 in bytes representation. 
message:
    1 <chunk> = message:
        1 <chunk> = empty chunk
        2 <chunk> = message:
            1 <chunk> = empty chunk
            2 <chunk> = message:
                1 <chunk> = "test"
                5 <chunk> = message:
                    1 <chunk> = message:
                        1 <chunk> = message:
                            1 <chunk> = "label1"
                            2 <chunk> = "label1-value1"
                        1 <chunk> = message:
                            1 <chunk> = "label2"
                            2 <chunk> = "label2-value1"
                        2 <64bit> = 0x16C999E4C5992E00 / 1642012747000000000 / 6.6891710e-199
                        3 <64bit> = 0x16C999E4C5992E00 / 1642012747000000000 / 6.6891710e-199
                        4 <64bit> = 0x0000000000000000 / 0 / 0.0000000 <--- here 0 is stored.
```

**Comment by CatherineF-dev** [comment]
Hi team, what would suggest for this case? Thanks!
1. drop this metric
2. set a default value = 0.0 when metric value is nil
3. others?

**Comment by tigrannajaryan** [comment]
Version 0.8.0 is not a stable metric proto version (stability was declared in 0.9.0), so breaking changes were allowed at the time.

I don't know what exactly we can do about it right now, but this seems to be too late to address from compatibility perspective.

Anything prevents you from upgrading all parties (senders and receivers) to a recent version so that you are using a stable OTLP version?

**Comment by CatherineF-dev** [comment]
Thanks Tigran!

 

> Anything prevents you from upgrading all parties (senders and receivers) to a recent version so that you are using a stable OTLP version?

Metric value 0.0 is lost. 

 > Version 0.8.0 is not a stable metric proto version (stability was declared in 0.9.0), so breaking changes were allowed at the time.

Okay, thanks! Will upgrade and use 0.9.0+.

**Comment by tigrannajaryan** [comment]
@CatherineF-dev Is there anything more to do or we can close this?

**Comment by CatherineF-dev** [comment]
No, from my side. Thanks!

Do we need to document that 0.8 -> 0.9 is not back-compatible? Or it has been mentioned in the Changelog.

**Comment by tigrannajaryan** [comment]
> No, from my side. Thanks!
> 
> Do we need to document that 0.8 -> 0.9 is not back-compatible? Or it has been mentioned in the Changelog.

It is in the changelog: https://github.com/open-telemetry/opentelemetry-proto/blob/main/CHANGELOG.md#changed-metrics
