### ISSUE TITLE
Does Gauge's value type has to be number data point?

### ISSUE THREAD

**Issue by singku** [open-telemetry/opentelemetry-proto#401]
What if we want string data point? E.g. software_version, OS name, etc.

**Comment by pirgeo** [comment]
The examples you gave seem like attributes that you can add to a gauge, but the gauge value itself should not hold the string. I am not sure what your use-case is, maybe you can elaborate a bit more?

**Comment by singku** [comment]
My use case is that we want to monitor Redis node's role, whether it's `primary` or `replica`, so that we can monitor whether/when there will be failover. We expect to extract this role string directly from `info` output and emit it as a gauge metric value.

**Comment by pirgeo** [comment]
I am not sure this is a gauge use-case, this sounds more like an event to me ("notify me when something changed"). If you want the information of "We have 3 redis nodes running, one is `primary` and two are `replica` I would model this as Counters, and put the different attributes on it.
For the example above you would create 3 counters (one for each node, and they all share the same name):

| Redis node | Metric Name  | Attributes     | Value |
| ---------- | ------------ | -------------- | ----- |
| 1          | `redis.node` | `role=primary` | 1     |
| 2          | `redis.node` | `role=replica` | 1     |
| 3          | `redis.node.status` | `role=replica` | 1     |


Depending on your backend, this should give you a nice overview of how many nodes are in which state, over time. You can also export it as gauges, but I am not sure if all backends allow you to add together gauges. I think the default semantics is "last value" meaning that if one of

**Comment by singku** [comment]
@pirgeo  Thanks for the comments, I think this works for our case, the only change I would add is to change the value to be 0 and 1, to represents replica and primary. So that even for a single node we can graph it and view the changes of primary-ship. I proposed this PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11090, maybe you can take a look if interested.

**Comment by tigrannajaryan** [comment]
Closing the issue since nothing is needed in the proto. Please reopen if you think otherwise.
