### ISSUE TITLE
Enable health-check in the proto

### ISSUE THREAD

**Issue by anelson-splunk** [open-telemetry/opentelemetry-proto#418]
Enhancement: There should be a way to check the health of a gRPC service via a health check. This would be a great way for Kubernetes to determine of a container serving gRPC is available to handle requests before actually sending requests to the pod. It would also be helpful in an architecture that might have gRPC services behind a load balancer so that the load balancer knows the service is healthy before sending requests to the gRPC service.
https://github.com/grpc/grpc/blob/master/doc/health-checking.md

**Comment by tigrannajaryan** [comment]
What exactly enhancement is needed in OTLP? Isn't https://github.com/grpc/grpc/blob/master/doc/health-checking.md sufficient as a health check specification for any service that happens to receive OTLP?

**Comment by anelson-splunk** [comment]
Never-mind - my enhancement went to the wrong repository... I meant for it to go in https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver to add to the receiver a health check using the gRPC specification.
