### ISSUE TITLE
实现export方法时 traceid 字段编码无法直接解码

### ISSUE THREAD

**Issue by latte-go** [open-telemetry/opentelemetry-proto#447]
https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto

实现export方法时 traceid 字段编码无法直接解码 需要自己进行hex 解码然后进行json.marshal 才可以拿到traceid的真实内容

**Comment by tigrannajaryan** [comment]
OpenTelemetry uses English for communication. Please create issues in English.
