### ISSUE TITLE
Mark opentelemetry-proto repo 1.0

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-proto#456]
This is the checklist we want to go through before marking this repo 1.0.

All issues must be resolved, PRs must be merged or closed. Please add any items you think are missing to this list.

- [x] https://github.com/open-telemetry/opentelemetry-proto/pull/432
- [x] https://github.com/open-telemetry/opentelemetry-proto/issues/400 (same as the PR above)
- [x] https://github.com/open-telemetry/opentelemetry-specification/issues/3415 (strictly speaking not necessary, but would be nice to perform before 1.0).
- [x] https://github.com/open-telemetry/opentelemetry-proto/issues/433
- [x] https://github.com/open-telemetry/opentelemetry-proto/pull/423 (fix or won't fix)
- [x] https://github.com/open-telemetry/opentelemetry-proto/issues/473
- [x] https://github.com/open-telemetry/opentelemetry-proto/issues/476

**Comment by jmacd** [comment]
For the record, I think we should keep every existing enum as-is and declare 1.0.
I do not support #433 and I do not support #423.

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-approvers please add any other items to the checklist above that you think are needed before we mark this repo 1.0.

**Comment by marcalff** [comment]
Please consider to add a VERSION file as well, per issue #434 

(Not a spec approver, this is just a suggestion)

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-approvers I prepared the draft release 1.0.0: https://github.com/open-telemetry/opentelemetry-proto/releases/tag/untagged-c53594e61f023c410cc4

Is there anything that needs to be changed in this repo before we hit the release button?

**Comment by bogdandrutu** [comment]
One small comment related to this, is how are we going to allow adding of new signals after 1.0? Since we have these guarantees, any new signal is automatically stable? Are we going to have multiple versions? Would be good to understand that path for that, since there will be folks commenting that if we include that new signal in 1.0 you need to have it stable from the first release..

**Comment by tigrannajaryan** [comment]
Good questions!

> One small comment related to this, is how are we going to allow adding of new signals after 1.0?
> Since we have these guarantees, any new signal is automatically stable? 

No. We have a maturity table where signals are explicitly listed: https://github.com/open-telemetry/opentelemetry-proto#maturity-level

When adding a new signal we must also add a row in this table. New signals will get added as "Alpha" and then will mature over time.

>Are we going to have multiple versions? Would be good to understand that path for that, since there will be folks commenting that if we include that new signal in 1.0 you need to have it stable from the first release..

No, I think we should stay on 1.0 for now. OTLP 2.0 will be either for breaking changes or when we want to add something so big that even though it does not break existing stuff we want to increase the major version number.

@open-telemetry/specs-approvers Do we feel that any of these needs to be recorded as a text in the README or in docs sub-directory and not just as a comment in this issue?

**Comment by bogdandrutu** [comment]
I would like just a short sentence that the 1.0 artifact may include unstable/alpha components that can break

**Comment by tigrannajaryan** [comment]
> I would like just a short sentence that the 1.0 artifact may include unstable/alpha components that can break

@bogdandrutu see PR: https://github.com/open-telemetry/opentelemetry-proto/pull/489

**Comment by tigrannajaryan** [comment]
https://github.com/open-telemetry/opentelemetry-proto/pull/489 is merged.

Last call before 1.0.0 goes out.

**Comment by bogdandrutu** [comment]
@tigrannajaryan one more "nit" https://github.com/open-telemetry/opentelemetry-proto/pull/490

**Comment by bogdandrutu** [comment]
I think we are ready now, at least I have no more objections

**Comment by tigrannajaryan** [comment]
v1.0.0 released: https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v1.0.0

**Comment by marcalff** [comment]
@tigrannajaryan 

Please fix the CHANGELOG.

It reads:

```
## Unreleased

Full list of differences found in [this compare](https://github.com/open-telemetry/opentelemetry-proto/compare/v0.20.0...main).

## 0.20.0 - 2023-06-06

Full list of differences found in [this compare](https://github.com/open-telemetry/opentelemetry-proto/compare/v0.19.0...v0.20.0).
```

Expected:

```
## Unreleased

Full list of differences found in [this compare](https://github.com/open-telemetry/opentelemetry-proto/compare/v1.0.0...main).

## 1.0.0 - 2023-07-03

Full list of differences found in [this compare](https://github.com/open-telemetry/opentelemetry-proto/compare/v0.20.0...v1.0.0).

## 0.20.0 - 2023-06-06

Full list of differences found in [this compare](https://github.com/open-telemetry/opentelemetry-proto/compare/v0.19.0...v0.20.0).
```

**Comment by tigrannajaryan** [comment]
@marcalff PR to update changelog https://github.com/open-telemetry/opentelemetry-proto/pull/493
