### ISSUE TITLE
Mention 1.0.0 in CHANGELOG.md?

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry-proto#492]
I'm reviewing https://github.com/open-telemetry/opentelemetry.io/pull/2966, and was wondering why 1.0.0 isn't mentioned in https://github.com/open-telemetry/opentelemetry-proto/blob/main/CHANGELOG.md, even if only as an alias for 0.20.0?

/cc @svrnm @cartermp

**Comment by tigrannajaryan** [comment]
PR to update https://github.com/open-telemetry/opentelemetry-proto/pull/493

**Comment by marcalff** [comment]
Thanks for the fix.

Please close, fixed by #493
