### ISSUE TITLE
Rename Resource.labels to Resource.attributes

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-proto#50]
Most entities (e.g. #48) are using a common Attribute structure, but Resource calls them "labels". This introduces unnecessary cognitive overhead.

Proposal: rename to "attributes" to be consistent across all entities.

**Comment by tigrannajaryan** [comment]
Makes sense to me. We will also need to rename it in the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-resource.md

**Comment by SergeyKanzhelev** [comment]
@tigrannajaryan I see you already filed it: https://github.com/open-telemetry/opentelemetry-specification/issues/342 =)

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan I see you already filed it: [open-telemetry/opentelemetry-specification#342](https://github.com/open-telemetry/opentelemetry-specification/issues/342) =)

@SergeyKanzhelev yep, thanks for the link.  :-)

I need more approvals on the PR that implements it please https://github.com/open-telemetry/opentelemetry-specification/pull/344

**Comment by tigrannajaryan** [comment]
Fixed via https://github.com/open-telemetry/opentelemetry-proto/pull/70
