### ISSUE TITLE
Why TraceID and SpanID  are defined []byte type?

### ISSUE THREAD

**Issue by Lempossible** [open-telemetry/opentelemetry-proto#500]
When I'm useing json.Marshal(tradeData), the trace_id, span_id and parent_span_id in output are base64 encoded.
So I wonder why TraceID and SpanID  are defined []byte type?

**Comment by tigrannajaryan** [comment]
Are you asking about why the particular design choice was made in OTLP? The answer to that is that it was found to be the best fit for design goals: https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/design-goals.md

If you are asking what should be OTLP/JSON representation of trace id and span id see https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md#json-protobuf-encoding

**Comment by Lempossible** [comment]
Yes. So how trace id and span id in the output in expamle are not encoded?
https://github.com/open-telemetry/opentelemetry-proto/blob/v0.20.0/examples/trace.json

**Comment by tigrannajaryan** [comment]
> Yes. So how trace id and span id in the output in expamle are not encoded? https://github.com/open-telemetry/opentelemetry-proto/blob/v0.20.0/examples/trace.json

Examples are correct. trace id and span id are hex encoded. See the spec: https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md#json-protobuf-encoding
