### ISSUE TITLE
AnyValue diverging from spec on website

### ISSUE THREAD

**Issue by bripkens** [open-telemetry/opentelemetry-proto#501]
Hey folks,

we noticed that the [documentation on the OTel website](https://opentelemetry.io/docs/specs/otel/common/#attribute) for attributes and the OTLP definition for `AnyValue` are slightly different. More specifically, OTLP accepts a wider range of values – specifically `bytes` and `KeyValueList`. Consequently, some questions came up:

 - In what situation would one see a `bytes` or `KeyValueList`?
 - Should this be corrected on the website? Or maybe explained via a code comment in OTLP?

**OTLP**

https://github.com/open-telemetry/opentelemetry-proto/blob/81a296f9dba23e32d77f46d58c8ea4244a2157a6/opentelemetry/proto/common/v1/common.proto#L28-L40

**Website** ([source](https://opentelemetry.io/docs/specs/otel/common/#attribute))

<img width="957" alt="image" src="https://github.com/open-telemetry/opentelemetry-proto/assets/596443/7082b2e2-a9e7-487e-a5c3-29336382b338">

**Comment by tigrannajaryan** [comment]
Logs require it: https://opentelemetry.io/docs/specs/otel/logs/data-model/#type-any

There is an open spec issue to allow traces and metrics to also use KeyValueList: https://github.com/open-telemetry/opentelemetry-specification/issues/376

**Comment by bripkens** [comment]
Awesome, thank you for the clarification @tigrannajaryan!
