### ISSUE TITLE
Fix releasing notes

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-proto#508]
The [RELEASING.md](https://github.com/open-telemetry/opentelemetry-proto/blob/main/RELEASING.md) notes reference creating release branches which don't appear to exist: https://github.com/open-telemetry/opentelemetry-proto/branches

Can someone who has recently performed the release update the notes with the process? 

Ran into this because we copied the releasing workflow for [opentelemetry-configuration](https://github.com/open-telemetry/opentelemetry-configuration) and ran into missing branch protection rules.

**Comment by arminru** [comment]
I think we'll also have to create a tag protection rule here:
https://github.com/open-telemetry/opentelemetry-proto/settings/tag_protection

**Comment by arminru** [comment]
@tigrannajaryan can you take a look?
Otherwise I can also update the docs and add a rule as described.

**Comment by tigrannajaryan** [comment]
We don't do release branches. We use the release function in github which adds tags.
