### ISSUE TITLE
Fail to push limit

### ISSUE THREAD

**Issue by gauravmanerkar** [open-telemetry/opentelemetry-proto#527]
Facing error "Fail to push limit" from `google/protobuf` after updating the package from 1.0 to 1.1.

May be the root cause lies in this package which uses `google/protobuf` as dependency.

I am facing the problem on cloud hosting environment and not on local.

```
The website encountered an unexpected error. Please try again later.

Google\Protobuf\Internal\GPBDecodeException: Error occurred during parsing: Fail to push limit. in Google\Protobuf\Internal\CodedInputStream->pushLimit() (line 340 of /code/vendor/google/protobuf/src/Google/Protobuf/Internal/CodedInputStream.php).
```

**Comment by tigrannajaryan** [comment]
Please provide more information about what exactly you are trying to do. 

Note that this repository is normally not intended for consumption by OpenTelemetry users. Instead you should use one of the OpenTelemetry language SDKs.

**Comment by gauravmanerkar** [comment]
Package `open-telemetry/gen-otlp-protobuf` contains compiled PHP code. When deployed to cloud hosting, the compiled files gets modified (may be by git) and it reports following error-

```
The website encountered an unexpected error. Please try again later.

Google\Protobuf\Internal\GPBDecodeException: Error occurred during parsing: Fail to push limit. in Google\Protobuf\Internal\CodedInputStream->pushLimit() (line 340 of /code/vendor/google/protobuf/src/Google/Protobuf/Internal/CodedInputStream.php).
```

Solution:
Add`.gitattributes`  with content `*.php -text diff` for following packages in package root folder .
like,
```
vendor/open-telemetry/.gitattributes
vendor/google/.gitattributes
```

**Comment by tigrannajaryan** [comment]
> Package `open-telemetry/gen-otlp-protobuf` contains compiled PHP code.

Where do you get this package from?

**Comment by gauravmanerkar** [comment]
https://github.com/opentelemetry-php/gen-otlp-protobuf.git

**Comment by tigrannajaryan** [comment]
It is best to take this to [https://github.com/opentelemetry-php](https://github.com/opentelemetry-php/gen-otlp-protobuf.git) which is not part of OpenTelemetry.
