### ISSUE TITLE
Retryable HTTP Statuses should be configurable

### ISSUE THREAD

**Issue by haus** [open-telemetry/opentelemetry-proto#531]
The OTLP spec lists 502, 503 and 504 as the only retryable 50x status codes. However some servers (and some CDNs) return a 500, even though it isn't the most appropriate status code, as a generic "something went wrong serving that request".
For cases where the remote server may return a 500 for retryable conditions, it would be useful if the retryable http statuses could be extended or configured to include it.

**Comment by tigrannajaryan** [comment]
I don't know if we want to do anything in the protocol specification about it. Implementations of OTLP client can decide how to deal with non-compliant servers. I suggest posting this as an enhancement request to the particular OTLP client implementation. If this behavior is universally needed it may be worth considering to add it as a configuration option of OTLP exporter in the [spec repo](https://github.com/open-telemetry/opentelemetry-specification).

**Comment by haus** [comment]
Sounds good. Since I think this applies generally to the server side it seems like it might be worth considering universally.

**Comment by arminru** [comment]
For reference: continued in https://github.com/open-telemetry/opentelemetry-specification/issues/3876.
