### ISSUE TITLE
File Makefile with executable permissions

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-proto#540]
The file `Makefile` has execute permissions in the github repository.

Is this intended ?

https://github.com/open-telemetry/opentelemetry-proto/blob/main/Makefile

**Comment by carlosalberto** [comment]
Sounds it was not done on purpose, yes. @bogdandrutu @tigrannajaryan maybe you remember?

**Comment by tigrannajaryan** [comment]
Yes, likely accidental. No reason for it to be executable.
