### ISSUE TITLE
Define relationship between profile messages and pprof

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-proto#545]
Does this effectively represent a fork of the upstream definition [here](https://github.com/google/pprof/blob/main/proto/profile.proto)? It seems like it must be we likely have different versioning rules than whatever governs the upstream.

It seems valuable to have comments explaining the relationship between this file and upstream pprof.

_Originally posted by @jack-berg in https://github.com/open-telemetry/opentelemetry-proto/pull/534#discussion_r1552393303_

**Comment by tigrannajaryan** [comment]
@open-telemetry/profiling-maintainers It would be very useful to produce a diff between Otel profiles proto and pprof proto definitions and annotate the differences with explanations.

**Comment by tigrannajaryan** [comment]
This is no longer necessary after [decision made here](https://github.com/open-telemetry/opentelemetry-proto/issues/567#issuecomment-2286565449).
