### ISSUE TITLE
Proposal: convert Tracestate to an unstructured raw string field in Span

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-proto#55]
The `Span.tracestate` field is currently a structured data that stores fully decoded Tracestate. However, there does not seem to be a good use case for keeping this in structured form, there are no known applications that work with this elements of this data, other than just passing it around fully.

I suggest to  eliminate `Tracestate` message type and make `Span.tracestate` a simple string field in w3c-trace-context format.

This has been previously discussed as part of https://github.com/open-telemetry/oteps/pull/59#discussion_r334727805 and decided to be addressed in a separate PR.

**Comment by tigrannajaryan** [comment]
@yurishkuro @bogdandrutu I need your opinion on this, please.

**Comment by yurishkuro** [comment]
+1. It means less work for the tracer to package this data.
