### ISSUE TITLE
Example JSONs use wrong key name cases

### ISSUE THREAD

**Issue by swamisriman** [open-telemetry/opentelemetry-proto#565]
The JSON keys in the [example files](https://github.com/open-telemetry/opentelemetry-proto/tree/main/examples) use camel case where as the fields are defined in [.proto files](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto) in snake case.
This is causing issues with JSON parsing.
For reference, see issue: https://github.com/open-telemetry/opentelemetry-proto-go/issues/176

**Comment by tigrannajaryan** [comment]
The examples look correct to me. The [spec says](https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md#json-protobuf-encoding):

>The keys of JSON objects are **field names converted to lowerCamelCase**. Original field names are not valid to use as keys for JSON objects. For example, this is a valid JSON representation of a Resource: { "attributes": {...}, "droppedAttributesCount": 123 }, and this is NOT a valid representation: { "attributes": {...}, "dropped_attributes_count": 123 }.

**Comment by swamisriman** [comment]
Yes @tigrannajaryan 

The examples are fine.
I was using wrong package to marshall and unmarshall jsons

Ref: https://github.com/open-telemetry/opentelemetry-proto-go/issues/176#issuecomment-2147055182
