### ISSUE TITLE
Should we support fractional count in SummaryValue

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-proto#59]
See discussion here https://github.com/open-telemetry/opentelemetry-proto/pull/51#discussion_r346612319

**Comment by jmacd** [comment]
Common statsd metrics APIs support entering metric updates with a weight. We have not discussed type of support at the API level, but at the protocol level it seems more important to consider now.

The use I have in mind is generating metric summaries from a stream of spans.  If the spans are sampled, they may have non-integer counts. I would connect this issue with https://github.com/open-telemetry/opentelemetry-specification/pull/180.

**Comment by tigrannajaryan** [comment]
>Common statsd metrics APIs support entering metric updates with a weight. 

@jmacd Can you please post a relevant link here?

**Comment by cory-signalfx** [comment]
(hello, first time talker)

There's not a real spec for StatsD, but insofar as there are defacto standards [this is a reasonable one](https://github.com/b/statsd_spec). [Here is the sampling for counters](https://github.com/b/statsd_spec#counters).

I know at least [Stripe's Veneur](https://github.com/stripe/veneur) supports a sample rate on histograms too…

**Comment by jmacd** [comment]
For example, the Datadog statsd Count method contains a float64 "rate" parameter.
https://godoc.org/github.com/DataDog/datadog-go/statsd#Client.Count

In the statsd protocol, the count and sample rate are reported as separate fields. It would be reasonable, at least for discussing Summary values, to keep an integer count and a total sample weight adjustment as a separate multiplier. I'm starting to think we should close this.

**Comment by jmacd** [comment]
@cory-signalfx on the topic of statsd specifications, (sorry this is off-topic), do you know of any standard documents used by Veneur for the dogstatsd syntax for metric labels? I'm looking for comments to finish out https://github.com/open-telemetry/opentelemetry-go/pull/326

I'd like to discuss this sort of thing with you in https://gitter.im/open-telemetry/metrics-specs, thanks.

**Comment by jmacd** [comment]
Closing this in favor of #73.
