### ISSUE TITLE
Proposal: Renamed TimedEvent to Event

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-proto#60]
Following PR #56.

I'm glad to see that there is only one kind of Event represented here. I think, now, we should rename TimedEvent to Event. "Timed" implies that a duration is being recorded to me. These are timestamped events, and since there's not two Event types now I think we should just call it Event.

**Comment by tigrannajaryan** [comment]
Sounds good to me. If there are no objections I will make the change.

**Comment by yurishkuro** [comment]
is change to the spec required as well?

**Comment by bogdandrutu** [comment]
I think we called the API "AddEvent" so not "Timed" used in the specs.
