### ISSUE TITLE
Consider to remove Resource from Metrics and Spans

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-proto#68]
With the newly added ResourceMetrics and ResourceSpans messages it is not clear what is the benefit in having Resource as part of the Metric/Span definition is.

**Comment by tigrannajaryan** [comment]
I don't see any benefits. The `Resource` that needs to be associated with an individual `Span` or `Metric` can be equally well represented in an individual `ResourceMetrics` and `ResourceSpans` message.
I will raise a PR to eliminate Resource field.

**Comment by bogdandrutu** [comment]
Yes, with the newly added message you just create a message with one span if needed. It is one extra allocation but that it is fine because removes all the complicated logic on what Resource has the Span. Also the option was added before because we couldn't send spans with different Resources in OpenCensus protocol.
