### ISSUE TITLE
Zero means unknown for child span count

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-proto#76]
I think it is important to discuss [this](https://github.com/open-telemetry/opentelemetry-proto/pull/72#discussion_r351121524). Copying some notes from the thread. Note, that the main problem is that semantics of the field and how it will be used is not clearly defined.

Let's treat 0 as “unknown”. It has the same practical result that it can’t be used for validation, but it works better with an optional field.

If one simply forgot to set this property to any value - it will mean 0 children which may be factually incorrect.

Depending on semantics of the field and how it should be used there may be no practical difference. Validation is only useful when this value > 0.

**Comment by tigrannajaryan** [comment]
I don't mind doing this change. Just a couple thoughts:

>If one simply forgot to set this property to any value - it will mean 0 children which may be factually incorrect.

I guess what you are saying is that if a sender forgets to set any value then it is not possible for receiver to detect that it was not set and it should not be used. This is in contrast to other numeric fields where if one forgets to set the value the receiver has a good change to detect that something is wrong (e.g. if start_time_unixnano is 0 the receiver can easily detect it and treat it as bad data).

I agree with this line of thinking.

>Depending on semantics of the field and how it should be used there may be no practical difference. Validation is only useful when this value > 0.

This makes sense to me. We will need to specify that value of 0 should not be used for validation purposes.

**Comment by bogdandrutu** [comment]
This filed was removed
