### ISSUE TITLE
Link type is missing from the protocol

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-proto#86]
Both OpenCensus and Jaeger have the concept of link type. Not having this concept in the proto makes it difficult to perform lossless translation between the formats, which is one of the use cases for this proto.

**Comment by SergeyKanzhelev** [comment]
related: https://github.com/open-telemetry/opentelemetry-specification/issues/65

**Comment by bogdandrutu** [comment]
Closing this since link type is no longer a thing
