### ISSUE TITLE
Span tracestate incorrect type

### ISSUE THREAD

**Issue by hectorhdzg** [open-telemetry/opentelemetry-proto#98]
OpenTelemetry Span tracestate is currently a [string](https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/trace/v1/trace.proto#L70) and an object in [OpenCensus](https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/trace/v1/trace.proto#L84) 

If string will be used in this protocol it would be good to specify more details about it

**Comment by tigrannajaryan** [comment]
The [comment](https://github.com/open-telemetry/opentelemetry-proto/blob/a7a235db6b05a921b06ba1deb6adcbe43343cdb6/opentelemetry/proto/trace/v1/trace.proto#L67) for tracestate field says:
```
// tracestate conveys information about request position in multiple distributed tracing graphs.
// It is a tracestate in w3c-trace-context format: https://www.w3.org/TR/trace-context/#tracestate-header
// See also https://github.com/w3c/distributed-tracing for more details about this field.
```
What other details are you looking for?

**Comment by hectorhdzg** [comment]
Thanks @tigrannajaryan for confirmation after further reading I realize there are tons of details in w3 docs

**Comment by tigrannajaryan** [comment]
Closing the issue, please reopen if more details are needed.
